#!/usr/bin/env python3
"""Generate every scene of the "views vs clients" reel (hook hub included).

Each graphic scene: listicle-crimson background, optional breadcrumb, headline, and its own graphic. Cutaways are
full-screen footage with an optional overlay. All times are GLOBAL voice-over seconds (transcript.json); `at(t)`
converts to scene-local time.
    python3 tools/gen_scenes.py
"""
import html
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONTS = (ROOT / "tools/fonts.css.snippet").read_text()
# same footage grade as the strip (see tools/assemble.py)
GRADE = html.escape(json.dumps(json.loads((ROOT / "tools/grade.json").read_text()), separators=(",", ":")))
CHECK = '<svg width="34" height="34" viewBox="0 0 34 34"><path d="M7 18 L14 25 L27 10" fill="none" stroke="#fff" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/></svg>'
ICON_VIEWS = '<svg viewBox="0 0 54 54"><rect x="3" y="3" width="48" height="48" rx="12" fill="#c2304b"/><path d="M9 27 C 15 17, 39 17, 45 27 C 39 37, 15 37, 9 27 Z" fill="none" stroke="#fff" stroke-width="3.6" stroke-linejoin="round"/><circle cx="27" cy="27" r="5.5" fill="#fff"/></svg>'
ICON_CLIENTS = '<svg viewBox="0 0 54 54"><rect x="3" y="3" width="48" height="48" rx="12" fill="#e0902a"/><rect x="11" y="19" width="32" height="22" rx="4" fill="#fff"/><path d="M21 19 V15 a2 2 0 0 1 2 -2 h8 a2 2 0 0 1 2 2 V19" stroke="#fff" stroke-width="3.4" fill="none"/><path d="M11 28 H43" stroke="#e0902a" stroke-width="2.6"/></svg>'
HEART = '<svg viewBox="0 0 40 36"><path d="M20 34 C 8 25, 2 18, 2 11 a9 9 0 0 1 18 -3 a9 9 0 0 1 18 3 c0 7 -6 14 -18 23 Z" fill="#e0324f"/></svg>'


def panel(sid, t0, t1, css, body, js, aura=(160, 360), crumb=None):
    p = sid.split("-")[0]
    crumb_html = ""
    crumb_js = ""
    if crumb:
        crumb_html = (f'<div class="lc-crumb" id="{p}-crumb"><i class="tl"></i><i class="tr"></i><i class="bl"></i><i class="br"></i>'
                      f'<span class="k">{crumb[0]}</span><span class="v">{crumb[1]}</span></div>')
        crumb_js = f'tl.fromTo("#{p}-crumb", {{ opacity: 0, y: -18 }}, {{ opacity: 1, y: 0, duration: 0.35, ease: "power3.out" }}, 0.03);'
    html = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <!-- Generated by tools/gen_scenes.py: edit the generator, not this file. -->
    <template id="{sid}-template">
      <link rel="stylesheet" href="assets/css/components.css" />
      <link rel="stylesheet" href="assets/css/house.css" />
      <style>
{FONTS}{css}
      </style>
      <div id="{p}-root" class="scene-root" data-composition-id="{sid}" data-width="1080" data-height="1920">
        <div class="lc-bg"><div class="lc-grid" data-layout-allow-overflow></div><div class="lc-aura" id="{p}-aura" style="left: {aura[0]}px; top: {aura[1]}px" data-layout-allow-overflow></div><div class="lc-vignette"></div></div>
        {crumb_html}
{body}
      </div>
      <script>
        (function () {{
          const T0 = {t0};
          const at = (t) => Math.max(0, t - T0);
          const tl = gsap.timeline({{ paused: true }});
          const root = document.getElementById("{p}-root");
          fx.ambient(tl, root, {t1 - t0:.2f});
          {crumb_js}
{js}
          window.__timelines["{sid}"] = tl;
        }})();
      </script>
    </template>
  </body>
</html>
"""
    (ROOT / f"compositions/{sid}.html").write_text(html)


def cut(sid, t0, t1, media_start, origin="50% 26%", s0=1.0, s1=1.1, y1=0, rate=1.0, over_css="", over_html="", over_js=""):
    """Full-screen cutaway of the user's footage, with an optional overlay (times in global seconds via at())."""
    p = sid.split("-")[0]
    html = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <!-- Generated by tools/gen_scenes.py. Full-screen cutaway of the user's footage. -->
    <template id="{sid}-template">
      <link rel="stylesheet" href="assets/css/components.css" />
      <link rel="stylesheet" href="assets/css/house.css" />
      <style>
{FONTS}        #{p}-root {{ position: absolute; inset: 0; overflow: hidden; background: #0b0b0b; }}
        #{p}-cam {{ position: absolute; inset: 0; transform-origin: {origin}; }}
        #{p}-cam video {{ position: absolute; left: 0; top: 0; width: 1080px; height: 1920px; object-fit: cover; }}
        #{p}-shade {{ position: absolute; inset: 0; background: radial-gradient(ellipse 80% 60% at 50% 32%, rgba(0,0,0,0) 0%, rgba(0,0,0,0.45) 100%), linear-gradient(180deg, rgba(0,0,0,0) 50%, rgba(0,0,0,0.45) 100%); }}
{over_css}
      </style>
      <div id="{p}-root" data-composition-id="{sid}" data-width="1080" data-height="1920">
        <div id="{p}-cam">
          <video id="{p}-v" class="clip" data-color-grading="{GRADE}" src="assets/video/desk.mp4" data-start="0" data-duration="{t1 - t0:.2f}" data-media-start="{media_start}" data-playback-rate="{rate}" data-track-index="0" muted playsinline></video>
        </div>
        <div id="{p}-shade"></div>
{over_html}
      </div>
      <script>
        (function () {{
          const T0 = {t0};
          const at = (t) => Math.max(0, t - T0);
          const tl = gsap.timeline({{ paused: true }});
          tl.fromTo("#{p}-cam", {{ scale: {s0 + 0.12}, filter: "blur(10px)" }}, {{ scale: {s0}, filter: "blur(0px)", duration: 0.3, ease: "power3.out" }}, 0);
          tl.to("#{p}-cam", {{ scale: {s1}, y: {y1}, duration: {t1 - t0 - 0.3:.2f}, ease: "sine.inOut" }}, 0.3);
{over_js}
          window.__timelines["{sid}"] = tl;
        }})();
      </script>
    </template>
  </body>
</html>
"""
    (ROOT / f"compositions/{sid}.html").write_text(html)


def tile(tid, icon, num, name, left, top, cls=""):
    return (f'<div class="lc-tile vt {cls}" id="{tid}" style="left: {left}px; top: {top}px"><span class="ico">{icon}</span>'
            f'<span class="rule"></span><span class="n">{num}</span><span class="nm">{name}</span></div>')


TILE_CSS = """
        .vt { width: 240px; height: 214px; }
        .vt .ico { display: block; margin-top: 26px; width: 64px; height: 64px; }
        .vt .ico svg { display: block; width: 100%; height: 100%; }
        .vt .nm { margin-top: 4px; font-weight: 800; font-size: 34px; letter-spacing: -0.03em; line-height: 1.05; text-align: center; }"""

# six polished "beautiful work" cards (abstract UI, no text)
LOOKS = [("#111", "#e0324f"), ("#f2f2f2", "#111"), ("#1a1714", "#e0902a"), ("#f6efe6", "#c26b2e"), ("#0f0f10", "#f5f5f5"), ("#f3eef2", "#99122b")]


def work_cards(prefix, xy, w=280, h=190):
    out = []
    for i, ((x, y, r), (bg, ac)) in enumerate(zip(xy, LOOKS)):
        out.append(
            f'<div class="wk {prefix}-c" id="{prefix}-c{i}" style="left: {x}px; top: {y}px; width: {w}px; height: {h}px; background: {bg}" data-r="{r}">'
            f'<i style="left: 16px; top: 16px; width: 70px; height: 10px; background: {ac}"></i>'
            f'<i style="left: 16px; top: 44px; width: 150px; height: 22px; background: {ac}; opacity: 0.85"></i>'
            f'<i style="left: 16px; top: 74px; width: 110px; height: 22px; background: {ac}; opacity: 0.6"></i>'
            f'<i style="left: {w - 104}px; top: 40px; width: 88px; height: {h - 70}px; background: {ac}; opacity: 0.35"></i>'
            f'<i style="left: 16px; top: {h - 62}px; width: 70px; height: 24px; border-radius: 12px; background: {ac}"></i></div>')
    return "\n        ".join(out)


WORK_CSS = """
        .wk { position: absolute; border-radius: 14px; overflow: hidden; border: 2px solid rgba(255,255,255,0.22); box-shadow: 0 0 26px rgba(255,255,255,0.08), 0 30px 60px rgba(0,0,0,0.6); }
        .wk i { position: absolute; display: block; border-radius: 5px; }"""


def main():
    # ---------------------------------------------------------------- s01 hook hub: views or clients?
    panel("s01-hub-hook", 0.0, 3.83, TILE_CSS + """
        #s01-l1 { font-size: 88px; }
        #s01-t1 { left: 110px; top: 640px; }
        #s01-t2 { left: 730px; top: 640px; }
        #s01-ball { left: 425px; top: 632px; }
        #s01-ball span { position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; }
        #s01-neq { font-size: 130px; opacity: 0; }
    """, f"""
        <div class="lc-hub" id="s01-hub"><span class="l1" id="s01-l1"><span id="s01-a">Views</span> <span id="s01-b">Or Clients?</span></span><span class="l2" id="s01-l2">Not The Same Thing</span></div>
        {tile("s01-t1", ICON_VIEWS, "01", "Views", 110, 640)}
        {tile("s01-t2", ICON_CLIENTS, "02", "Clients", 730, 640)}
        <div class="lc-ball" id="s01-ball"><span id="s01-vs">vs</span><span id="s01-neq">≠</span></div>
    """, """
          fx.typeSpan(tl, "#s01-a", at(0.38), at(0.86));
          fx.typeSpan(tl, "#s01-b", at(1.18), at(2.22));
          fx.typeSpan(tl, "#s01-l2", at(2.78), at(3.70));
          tl.fromTo("#s01-t1", { opacity: 0, scale: 0.6, rotation: -8, filter: "blur(14px)" }, { opacity: 1, scale: 1, rotation: -4, filter: "blur(0px)", duration: 0.5, ease: "expo.out" }, at(0.40));
          tl.fromTo("#s01-t2", { opacity: 0, scale: 0.6, rotation: 8, filter: "blur(14px)" }, { opacity: 1, scale: 1, rotation: 4, duration: 0.5, filter: "blur(0px)", ease: "expo.out" }, at(1.62));
          tl.fromTo("#s01-ball", { scale: 0.3, opacity: 0 }, { scale: 1, opacity: 1, duration: 0.55, ease: "back.out(1.8)" }, at(1.18));
          tl.to("#s01-t1", { y: -14, duration: 2.6, ease: "sine.inOut" }, at(0.9));
          tl.to("#s01-t2", { y: 12, duration: 1.9, ease: "sine.inOut" }, at(2.1));
          // "not the same thing": vs becomes ≠, the two tiles push apart
          tl.to("#s01-vs", { opacity: 0, scale: 0.5, duration: 0.18, ease: "power2.in" }, at(2.88));
          tl.fromTo("#s01-neq", { opacity: 0, scale: 1.8 }, { opacity: 1, scale: 1, duration: 0.3, ease: "back.out(2.2)", immediateRender: false }, at(3.03));
          tl.to("#s01-t1", { x: -30, duration: 0.5, ease: "power3.out" }, at(3.09));
          tl.to("#s01-t2", { x: 30, duration: 0.5, ease: "power3.out" }, at(3.09));
    """, aura=(160, 300))

    # ---------------------------------------------------------------- s02 millions of views, hundreds of thousands of likes
    hearts = "\n".join(f'        <span class="s02-h" style="left: {x}px; top: 1040px">{HEART}</span>' for x in (620, 700, 780, 860, 660, 820))
    panel("s02-millions", 3.83, 7.31, """
        #s02-head { top: 250px; font-size: 66px; }
        .s02-card { top: 430px; width: 430px; height: 440px; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 18px; }
        #s02-c1 { left: 85px; }
        #s02-c2 { left: 565px; }
        .s02-card .ic { width: 96px; height: 96px; display: flex; align-items: center; justify-content: center; border-radius: 50%; background: rgba(184,25,58,0.18); border: 2px solid rgba(184,25,58,0.7); }
        .s02-card .big-num { font-size: 130px; }
        .s02-card .lb { font-weight: 700; font-size: 38px; color: #bdbbb8; }
        .s02-h { position: absolute; width: 56px; height: 50px; z-index: 4; }
        .s02-h svg { width: 100%; height: 100%; display: block; }
    """, f"""
        <div class="lc-head" id="s02-head"><span id="s02-h1">Millions</span><span class="lc-it" id="s02-h2">Of Views</span></div>
        <div class="gl s02-card" id="s02-c1"><span class="ic"><svg width="62" height="62" viewBox="0 0 54 54"><path d="M5 27 C 13 14, 41 14, 49 27 C 41 40, 13 40, 5 27 Z" fill="none" stroke="#f5f5f5" stroke-width="4" stroke-linejoin="round"/><circle cx="27" cy="27" r="7" fill="#f5f5f5"/></svg></span><span class="big-num" id="s02-n1">0</span><span class="lb">views</span></div>
        <div class="gl s02-card" id="s02-c2"><span class="ic"><svg width="56" height="50" viewBox="0 0 40 36"><path d="M20 34 C 8 25, 2 18, 2 11 a9 9 0 0 1 18 -3 a9 9 0 0 1 18 3 c0 7 -6 14 -18 23 Z" fill="#f5f5f5"/></svg></span><span class="big-num" id="s02-n2">0</span><span class="lb">likes</span></div>
{hearts}
    """, """
          fx.typeSpan(tl, "#s02-h1", at(4.05), at(4.48));
          fx.typeSpan(tl, "#s02-h2", at(4.49), at(4.96));
          fx.blurIn(tl, "#s02-c1", at(3.88));
          fx.blurIn(tl, "#s02-c2", at(5.40));
          fx.count(tl, "#s02-n1", 0, 1, at(4.05), 0.85, (v) => (v >= 0.999 ? "1M+" : Math.round(v * 999) + "K"));
          fx.count(tl, "#s02-n2", 0, 100, at(5.54), 1.0, (v) => (v >= 99.5 ? "100K+" : Math.round(v) + "K"));
          root.querySelectorAll(".s02-h").forEach((el, i) => {
            tl.fromTo(el, { opacity: 0, y: 0, scale: 0.4, rotation: [-12, 8, -6, 10, -8, 6][i] }, { opacity: 1, y: -60, scale: 1, duration: 0.35, ease: "back.out(2)" }, at(5.70 + i * 0.16));
            tl.to(el, { y: -150, x: [-30, 20, -10, 30, -20, 10][i], opacity: 0, duration: 1.0, ease: "power1.in" }, at(6.05 + i * 0.16));
          });
          tl.fromTo("#s02-c1", { boxShadow: "0 0 30px rgba(255,255,255,0.07), 0 40px 90px rgba(0,0,0,0.7)" }, { boxShadow: "0 0 90px rgba(184,25,58,0.8), 0 40px 90px rgba(0,0,0,0.7)", duration: 0.25, yoyo: true, repeat: 1, ease: "power2.out", immediateRender: false }, at(4.90));
    """, aura=(160, 380))

    # ---------------------------------------------------------------- s03 bank account still showed zero
    panel("s03-zero", 7.31, 9.37, """
        #s03-head { top: 250px; font-size: 66px; }
        #s03-card { left: 140px; top: 440px; width: 800px; height: 470px; }
        #s03-card .hd { font-size: 34px; }
        #s03-bal { position: absolute; left: 0; right: 0; top: 110px; text-align: center; font-size: 210px; }
        #s03-card svg { position: absolute; left: 60px; top: 360px; width: 680px; height: 60px; overflow: visible; }
    """, """
        <div class="lc-head" id="s03-head"><span id="s03-h1">Bank Account:</span><span class="lc-it" id="s03-h2">Still Zero</span></div>
        <div class="gl" id="s03-card"><span class="hd">Bank account</span><span class="big-num" id="s03-bal">$0</span>
          <svg viewBox="0 0 680 60"><path d="M0 30 H680" stroke="rgba(255,255,255,0.18)" stroke-width="3" stroke-dasharray="10 10" fill="none" /><path class="lc-wire" id="s03-l" d="M0 30 H680" pathLength="1" stroke-dasharray="1" stroke-dashoffset="1" /></svg></div>
    """, """
          fx.typeSpan(tl, "#s03-h1", at(7.56), at(8.08));
          fx.typeSpan(tl, "#s03-h2", at(8.09), at(9.02));
          fx.blurIn(tl, "#s03-card", at(7.34));
          fx.draw(tl, "#s03-l", at(7.6), 1.0);
          // "zero": the balance thumps, the card turns crimson
          tl.fromTo("#s03-bal", { scale: 1, color: "#f5f5f5" }, { scale: 1.16, color: "#ff4d63", duration: 0.16, ease: "power2.out", yoyo: true, repeat: 1, immediateRender: false }, at(8.64));
          tl.to("#s03-bal", { color: "#ff4d63", duration: 0.2 }, at(8.98));
          fx.shake(tl, "#s03-card", at(8.70), 10);
          tl.to("#s03-card", { borderColor: "rgba(184,25,58,0.85)", boxShadow: "0 0 50px rgba(184,25,58,0.45), 0 40px 90px rgba(0,0,0,0.7)", duration: 0.3 }, at(8.66));
    """, aura=(160, 380))

    # ---------------------------------------------------------------- s04 my work was beautiful
    grid = [(80, 440, -4), (400, 410, 3), (720, 440, -3), (80, 680, 3), (400, 650, -2), (720, 680, 4)]
    panel("s04-beautiful", 9.37, 10.92, WORK_CSS + """
        #s04-head { top: 250px; font-size: 66px; }
    """, f"""
        <div class="lc-head" id="s04-head"><span id="s04-h1">My Work Was</span><span class="lc-it" id="s04-h2">Beautiful</span></div>
        {work_cards("s04", grid)}
    """, """
          fx.typeSpan(tl, "#s04-h1", at(9.37), at(9.92));
          fx.typeSpan(tl, "#s04-h2", at(9.94), at(10.55));
          root.querySelectorAll(".s04-c").forEach((el, i) => {
            const r = parseFloat(el.dataset.r);
            tl.fromTo(el, { opacity: 0, scale: 0.6, rotation: r * 3, filter: "blur(12px)" }, { opacity: 1, scale: 1, rotation: r, filter: "blur(0px)", duration: 0.45, ease: "expo.out" }, at(9.42 + i * 0.09));
            tl.to(el, { y: [-12, 10, -10, 12, -8, 10][i], duration: 1.1, ease: "sine.inOut" }, at(9.9));
          });
    """, aura=(160, 380))

    # ---------------------------------------------------------------- s05 neither trust nor an image of expertise
    small = [(110, 860, -4), (410, 840, 3), (710, 860, -3)]
    panel("s05-no-trust", 10.92, 14.86, WORK_CSS + """
        #s05-head { top: 250px; font-size: 66px; }
        .s05-row { left: 140px; }
        .s05-row .strike { position: absolute; left: 140px; width: 560px; top: 55px; height: 7px; border-radius: 4px; background: #e0324f; box-shadow: 0 0 14px rgba(224,50,79,0.7); transform-origin: 0% 50%; }
        .s05-row .x { position: absolute; right: 34px; top: 30px; width: 56px; height: 56px; }
        .wk.s05-c { opacity: 0.35; }
    """, f"""
        <div class="lc-head" id="s05-head"><span id="s05-h1">It Created</span><span class="lc-it" id="s05-h2">Neither</span></div>
        <div class="row s05-row" id="s05-r1" style="top: 450px"><span class="tab"></span><span class="num">01</span><span class="txt">Trust</span><span class="strike" id="s05-s1"></span><svg class="x" id="s05-x1" viewBox="0 0 56 56"><circle cx="28" cy="28" r="26" fill="#99122b"/><path d="M19 19 L37 37 M37 19 L19 37" stroke="#fff" stroke-width="6" stroke-linecap="round"/></svg></div>
        <div class="row s05-row" id="s05-r2" style="top: 610px"><span class="tab"></span><span class="num">02</span><span class="txt">Expertise</span><span class="strike" id="s05-s2"></span><svg class="x" id="s05-x2" viewBox="0 0 56 56"><circle cx="28" cy="28" r="26" fill="#99122b"/><path d="M19 19 L37 37 M37 19 L19 37" stroke="#fff" stroke-width="6" stroke-linecap="round"/></svg></div>
        {work_cards("s05", small, 260, 176)}
    """, """
          fx.typeSpan(tl, "#s05-h1", at(11.06), at(11.64));
          fx.typeSpan(tl, "#s05-h2", at(11.65), at(11.97));
          root.querySelectorAll(".s05-c").forEach((el, i) => {
            const r = parseFloat(el.dataset.r);
            tl.fromTo(el, { opacity: 0, y: 30 }, { opacity: 0.35, y: 0, rotation: r, duration: 0.4, ease: "power3.out" }, at(10.96 + i * 0.08));
          });
          fx.blurIn(tl, "#s05-r1", at(11.62), { y: 0, blur: 8 });
          tl.fromTo("#s05-s1", { scaleX: 0 }, { scaleX: 1, duration: 0.3, ease: "power2.out" }, at(12.10));
          fx.pop(tl, "#s05-x1", at(12.20), { from: 0 });
          tl.to("#s05-r1", { opacity: 0.55, duration: 0.3 }, at(12.5));
          fx.blurIn(tl, "#s05-r2", at(12.97), { y: 0, blur: 8 });
          tl.fromTo("#s05-s2", { scaleX: 0 }, { scaleX: 1, duration: 0.3, ease: "power2.out" }, at(13.95));
          fx.pop(tl, "#s05-x2", at(14.05), { from: 0 });
          tl.to("#s05-r2", { opacity: 0.55, duration: 0.3 }, at(14.4));
    """, aura=(160, 360))

    # ---------------------------------------------------------------- s06 cutaway: people liked... then left. No prospects.
    cut_hearts = "\n".join(
        f'        <span class="s06-h" style="left: {x}px; top: {y}px">{HEART}</span>' for x, y in ((180, 980), (330, 900), (760, 960), (860, 860), (560, 1010)))
    cut("s06-cut-left", 14.86, 18.48, 5.6, rate=0.9, over_css="""
        .s06-h { position: absolute; width: 74px; height: 66px; z-index: 3; }
        .s06-h svg { width: 100%; height: 100%; display: block; filter: drop-shadow(0 6px 18px rgba(0,0,0,0.6)); }
        #s06-stamp { left: 115px; top: 700px; z-index: 4; font-size: 96px; white-space: nowrap; }
    """, over_html=f"""{cut_hearts}
        <div class="stamp" id="s06-stamp" data-layout-allow-overlap data-layout-allow-occlusion>NO PROSPECTS</div>""", over_js="""
          // "liked": hearts pop up... "then left": they fly off
          document.querySelectorAll("#s06-root .s06-h").forEach((el, i) => {
            tl.fromTo(el, { opacity: 0, scale: 0.3, rotation: [-12, 8, -6, 10, -8][i] }, { opacity: 1, scale: 1, duration: 0.35, ease: "back.out(2.2)" }, at(15.07 + i * 0.09));
            tl.to(el, { x: 1100, y: -260 - i * 40, rotation: 40, opacity: 0, duration: 0.7, ease: "power2.in" }, at(16.47 + i * 0.06));
          });
          fx.stamp(tl, "#s06-stamp", at(17.50), -8);
""")

    # ---------------------------------------------------------------- s07 content has to serve your business objectives
    panel("s07-objectives", 18.48, 22.21, """
        #s07-tile { left: 390px; top: 330px; width: 300px; height: 230px; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 14px; }
        #s07-tile .nm { font-weight: 800; font-size: 40px; letter-spacing: -0.03em; }
        #s07-svg { position: absolute; left: 0; top: 0; width: 1080px; height: 1920px; overflow: visible; }
        #s07-pill { left: 205px; top: 690px; font-size: 60px; }
        .s07-c { top: 940px; }
        #s07-c1 { left: 95px; }
        #s07-c2 { left: 405px; }
        #s07-c3 { left: 760px; }
    """, f"""
        <svg id="s07-svg" viewBox="0 0 1080 1920" data-layout-allow-overflow>
          <path class="lc-wire s07-w" d="M 470 560 C 470 620, 470 640, 470 688" pathLength="1" stroke-dasharray="1" stroke-dashoffset="1" />
          <path class="lc-wire s07-w" d="M 540 560 C 540 620, 540 640, 540 688" pathLength="1" stroke-dasharray="1" stroke-dashoffset="1" />
          <path class="lc-wire s07-w" d="M 610 560 C 610 620, 610 640, 610 688" pathLength="1" stroke-dasharray="1" stroke-dashoffset="1" />
          <path class="lc-wire-dash" id="s07-d" d="M 540 790 V 870 H 210 V 940 M 540 870 V 940 M 540 870 H 860 V 940" />
          <circle class="lc-node" id="s07-node" cx="540" cy="870" r="11" />
        </svg>
        <div class="gl" id="s07-tile"><svg width="80" height="80" viewBox="0 0 54 54"><rect x="3" y="3" width="48" height="48" rx="12" fill="#c2304b"/><path d="M21 16 L38 27 L21 38 Z" fill="#fff"/></svg><span class="nm" id="s07-nm">Your Content</span></div>
        <div class="lc-pill" id="s07-pill">Business Objectives</div>
        <div class="lc-chip s07-c" id="s07-c1">Trust</div>
        <div class="lc-chip s07-c" id="s07-c2">Expertise</div>
        <div class="lc-chip s07-c" id="s07-c3">Clients</div>
    """, """
          fx.blurIn(tl, "#s07-tile", at(18.52));
          fx.typeSpan(tl, "#s07-nm", at(18.81), at(19.50));
          fx.draw(tl, root.querySelectorAll(".s07-w"), at(20.06), 0.45, 0.06);
          fx.pop(tl, "#s07-pill", at(20.58), { rot0: -6, rot: 0 });
          tl.fromTo("#s07-d", { opacity: 0 }, { opacity: 1, duration: 0.25 }, at(21.15));
          fx.pop(tl, "#s07-node", at(21.15), { from: 0 });
          tl.fromTo(root.querySelectorAll(".s07-c"), { opacity: 0, y: 20 }, { opacity: 1, y: 0, duration: 0.3, ease: "power3.out", stagger: 0.12 }, at(21.25));
          tl.to("#s07-c3", { borderColor: "#e0324f", boxShadow: "0 0 30px rgba(224,50,79,0.6)", duration: 0.3 }, at(21.75));
    """, aura=(160, 360), crumb=("The Lesson", "Serve The Business"))

    # ---------------------------------------------------------------- s08 cutaway: I learned that the hard way
    cut("s08-cut-hard-way", 22.21, 23.86, 8.55, origin="50% 22%", s1=1.12)

    # ---------------------------------------------------------------- s09 CTA: follow me
    panel("s09-cta", 23.86, 29.60, TILE_CSS + """
        #s09-hub2 .l1 { visibility: hidden; }
        #s09-btn { position: absolute; left: 240px; top: 600px; width: 600px; height: 150px; border-radius: 75px; background: #99122b; border: 3px solid rgba(255,255,255,0.25); box-shadow: 0 0 50px rgba(184,25,58,0.55), 0 30px 70px rgba(0,0,0,0.6); display: flex; align-items: center; justify-content: center; gap: 20px; font-family: "Inter Tight", Arial, sans-serif; font-weight: 800; font-size: 64px; letter-spacing: -0.03em; color: #fff; }
        #s09-done { position: absolute; left: 240px; top: 600px; width: 600px; height: 150px; border-radius: 75px; background: #2a292b; border: 3px solid rgba(255,255,255,0.18); display: flex; align-items: center; justify-content: center; gap: 16px; font-family: "Inter Tight", Arial, sans-serif; font-weight: 800; font-size: 58px; color: #d8d6d3; opacity: 0; }
        #s09-ripple { position: absolute; left: 600px; top: 600px; width: 220px; height: 220px; border-radius: 50%; background: rgba(255,90,110,0.45); opacity: 0; }
        #s09-cursor { position: absolute; left: 660px; top: 700px; width: 70px; height: 86px; overflow: visible; z-index: 6; }
        .s09-t { top: 860px; }
        #s09-t2.on { border-color: rgba(224,50,79,0.9); }
    """, f"""
        <div class="lc-hub" id="s09-hub"><span class="l1" id="s09-a1">Web Designers</span><span class="l2" id="s09-a2">Follow Me</span></div>
        <div class="lc-hub" id="s09-hub2"><span class="l1">Web Designers</span><span class="l2"><span id="s09-b1">I'll Show You</span> <span class="lc-it" id="s09-b2">What Worked</span></span></div>
        {tile("s09-t1", ICON_VIEWS, "01", "Views", 220, 860, "s09-t")}
        {tile("s09-t2", ICON_CLIENTS, "02", "Clients", 620, 860, "s09-t")}
        <div id="s09-done" data-layout-allow-overlap><svg width="52" height="52" viewBox="0 0 52 52"><path d="M10 27 L21 38 L43 13" fill="none" stroke="#d8d6d3" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/></svg>Following</div>
        <div id="s09-btn"><svg width="54" height="54" viewBox="0 0 54 54"><path d="M27 8 V46 M8 27 H46" stroke="#fff" stroke-width="8" stroke-linecap="round"/></svg>Follow</div>
        <div id="s09-ripple"></div>
        <svg id="s09-cursor" viewBox="0 0 70 86"><path d="M6 4 L6 66 L22 52 L33 78 L45 73 L34 47 L56 47 Z" fill="#ffffff" stroke="#111" stroke-width="4" stroke-linejoin="round"/></svg>
    """, """
          fx.typeSpan(tl, "#s09-a1", at(24.48), at(25.28));
          fx.typeSpan(tl, "#s09-a2", at(25.63), at(26.20));
          fx.pop(tl, "#s09-btn", at(23.95), { from: 0.3, dur: 0.45, ease: "back.out(2.2)" });
          tl.fromTo("#s09-cursor", { opacity: 0, x: 260, y: 300 }, { opacity: 1, x: 0, y: 0, duration: 0.45, ease: "power3.out" }, at(25.0));
          // "follow": the button gets clicked
          tl.to("#s09-cursor", { scale: 0.82, duration: 0.07, ease: "power2.in" }, at(25.68));
          tl.to("#s09-cursor", { scale: 1, duration: 0.18, ease: "back.out(2)" }, at(25.75));
          tl.to("#s09-btn", { scale: 0.93, duration: 0.07, ease: "power2.in" }, at(25.68));
          tl.fromTo("#s09-ripple", { opacity: 1, scale: 0.1 }, { opacity: 0, scale: 1.6, duration: 0.55, ease: "power2.out", immediateRender: false }, at(25.68));
          tl.to("#s09-btn", { opacity: 0, duration: 0.14, ease: "power1.out" }, at(25.76));
          tl.fromTo("#s09-done", { opacity: 0, scale: 0.93 }, { opacity: 1, scale: 1, duration: 0.4, ease: "back.out(2.6)", immediateRender: false }, at(25.76));
          tl.to("#s09-cursor", { x: 140, y: 160, opacity: 0, duration: 0.5, ease: "power2.in" }, at(26.3));
          // "and I'll show you what worked": line 2 swaps; Views fades, Clients lights up
          tl.to("#s09-a2", { opacity: 0, filter: "blur(10px)", duration: 0.2, ease: "power2.in" }, at(26.95));
          fx.typeSpan(tl, "#s09-b1, #s09-b2", at(27.22), at(28.40), { hidden: true });
          tl.fromTo("#s09-t1", { opacity: 0, y: 50, filter: "blur(12px)", rotation: -4 }, { opacity: 1, y: 0, filter: "blur(0px)", rotation: -4, duration: 0.45, ease: "expo.out" }, at(26.98));
          tl.fromTo("#s09-t2", { opacity: 0, y: 50, filter: "blur(12px)", rotation: 4 }, { opacity: 1, y: 0, filter: "blur(0px)", rotation: 4, duration: 0.45, ease: "expo.out" }, at(27.10));
          tl.to("#s09-t1", { opacity: 0.4, scale: 0.92, duration: 0.4, ease: "power2.out" }, at(28.07));
          tl.to("#s09-t2", { scale: 1.08, borderColor: "rgba(224,50,79,0.95)", boxShadow: "0 0 50px rgba(224,50,79,0.55), 0 26px 50px rgba(0,0,0,0.6)", duration: 0.4, ease: "back.out(2)" }, at(28.07));
    """, aura=(160, 360))

    print("scenes written")


if __name__ == "__main__":
    main()
