#!/usr/bin/env python3
"""Generate the story scenes (everything except the hub cards, which tools/gen_hubs.py writes).

Each scene: listicle-crimson background, optional breadcrumb, headline, and its own graphic. All times are GLOBAL
voice-over seconds (transcript.json); `at(t)` converts to scene-local time.
    python3 tools/gen_scenes.py
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONTS = (ROOT / "tools/fonts.css.snippet").read_text()

# screen.mp4 (1080x608) inside a 936px-wide browser panel
PANEL_W = 936
SC = PANEL_W / 1080
PANEL_VH = round(608 * SC)  # 527
CHECK = '<svg width="34" height="34" viewBox="0 0 34 34"><path d="M7 18 L14 25 L27 10" fill="none" stroke="#fff" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/></svg>'


def panel(sid, t0, t1, css, body, js, aura=(160, 360), crumb=None):
    p = sid.split("-")[0]
    crumb_html = ""
    crumb_js = ""
    if crumb:
        crumb_html = (f'<div class="lc-crumb" id="{p}-crumb"><i class="tl"></i><i class="tr"></i><i class="bl"></i><i class="br"></i>'
                      f'<span class="k">{crumb[0]}</span><span class="v">{crumb[1]}</span></div>')
        crumb_js = f'tl.fromTo("#{p}-crumb", {{ opacity: 0, y: -18 }}, {{ opacity: 1, y: 0, duration: 0.35, ease: "power3.out" }}, 0.03);'
    html = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <!-- Generated by tools/gen_scenes.py: edit the generator, not this file. -->
    <template id="{sid}-template">
      <link rel="stylesheet" href="assets/css/components.css" />
      <link rel="stylesheet" href="assets/css/house.css" />
      <style>
{FONTS}{css}
      </style>
      <div id="{p}-root" class="scene-root" data-composition-id="{sid}" data-width="1080" data-height="1920">
        <div class="lc-bg"><div class="lc-grid" data-layout-allow-overflow></div><div class="lc-aura" id="{p}-aura" style="left: {aura[0]}px; top: {aura[1]}px" data-layout-allow-overflow></div><div class="lc-vignette"></div></div>
        {crumb_html}
{body}
      </div>
      <script>
        (function () {{
          const T0 = {t0};
          const at = (t) => Math.max(0, t - T0);
          const tl = gsap.timeline({{ paused: true }});
          const root = document.getElementById("{p}-root");
          fx.ambient(tl, root, {t1 - t0:.2f});
          {crumb_js}
{js}
          window.__timelines["{sid}"] = tl;
        }})();
      </script>
    </template>
  </body>
</html>
"""
    (ROOT / f"compositions/{sid}.html").write_text(html)


def cut(sid, t0, t1, media_start, origin="50% 28%", s0=1.0, s1=1.12, y1=0):
    p = sid.split("-")[0]
    html = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <!-- Generated by tools/gen_scenes.py. Full-screen cutaway of the user's footage. -->
    <template id="{sid}-template">
      <style>
        #{p}-root {{ position: absolute; inset: 0; overflow: hidden; background: #0b0b0b; }}
        #{p}-cam {{ position: absolute; inset: 0; transform-origin: {origin}; }}
        #{p}-cam video {{ position: absolute; left: 0; top: 0; width: 1080px; height: 1920px; object-fit: cover; }}
        #{p}-shade {{ position: absolute; inset: 0; background: radial-gradient(ellipse 80% 60% at 50% 32%, rgba(0,0,0,0) 0%, rgba(0,0,0,0.55) 100%), linear-gradient(180deg, rgba(0,0,0,0) 45%, rgba(0,0,0,0.5) 100%); }}
      </style>
      <div id="{p}-root" data-composition-id="{sid}" data-width="1080" data-height="1920">
        <div id="{p}-cam">
          <video id="{p}-v" class="clip" src="assets/video/desk.mp4" data-start="0" data-duration="{t1 - t0:.2f}" data-media-start="{media_start}" data-track-index="0" muted playsinline></video>
        </div>
        <div id="{p}-shade"></div>
      </div>
      <script>
        (function () {{
          const tl = gsap.timeline({{ paused: true }});
          tl.fromTo("#{p}-cam", {{ scale: {s0 + 0.12}, filter: "blur(10px)" }}, {{ scale: {s0}, filter: "blur(0px)", duration: 0.3, ease: "power3.out" }}, 0);
          tl.to("#{p}-cam", {{ scale: {s1}, y: {y1}, duration: {t1 - t0 - 0.3:.2f}, ease: "sine.inOut" }}, 0.3);
          window.__timelines["{sid}"] = tl;
        }})();
      </script>
    </template>
  </body>
</html>
"""
    (ROOT / f"compositions/{sid}.html").write_text(html)


def ring(rid, size, stroke, label_size, label="5s"):
    """Timer ring badge; draw it by tweening #<rid>-arc strokeDashoffset 1 -> 0."""
    r = size / 2 - stroke
    return (f'<div class="ringb" id="{rid}" style="width: {size}px; height: {size}px">'
            f'<svg viewBox="0 0 {size} {size}"><circle class="trk" cx="{size / 2}" cy="{size / 2}" r="{r}" stroke-width="{stroke}"/>'
            f'<circle class="arc" id="{rid}-arc" cx="{size / 2}" cy="{size / 2}" r="{r}" stroke-width="{stroke}" pathLength="1" '
            f'stroke-dasharray="1" stroke-dashoffset="1" transform="rotate(-90 {size / 2} {size / 2})"/></svg>'
            f'<span class="lbl" style="font-size: {label_size}px">{label}</span></div>')


def portfolio_card(cid, w, h):
    """A clean portfolio hero, as blurred placeholder bars (no fake copy)."""
    return (f'<div class="gl" id="{cid}" style="width: {w}px; height: {h}px"><div class="bar3"><i></i><i></i><i></i><b style="width: {w * 0.42:.0f}px"></b></div>'
            f'<span class="ph" style="position: absolute; left: 40px; top: 108px; width: {w * 0.5:.0f}px; height: 34px; background: rgba(255,255,255,0.75); filter: blur(1.5px)"></span>'
            f'<span class="ph" style="position: absolute; left: 40px; top: 164px; width: {w * 0.68:.0f}px"></span>'
            f'<span class="ph" style="position: absolute; left: 40px; top: 194px; width: {w * 0.56:.0f}px"></span>'
            f'<span style="position: absolute; left: 40px; top: 240px; width: 150px; height: 46px; border-radius: 23px; background: #99122b"></span>'
            + "".join(f'<span style="position: absolute; left: {40 + i * ((w - 80 - 32) / 3 + 16):.0f}px; top: {h - 150}px; width: {(w - 80 - 32) / 3:.0f}px; height: 110px; border-radius: 10px; background: rgba(255,255,255,{0.1 + i * 0.03:.2f})"></span>' for i in range(3))
            + '</div>')


def ck_row(rid, text, left, top, width):
    return (f'<div class="ckr" id="{rid}" style="left: {left}px; top: {top}px; width: {width}px">'
            f'<span class="ck"><b id="{rid}-b">{CHECK}</b></span><span>{text}</span></div>')


def main():
    # ---------------------------------------------------------------- s02 understood in 5 seconds
    panel("s02-five-seconds", 3.08, 7.21, """
        #s02-head { top: 250px; font-size: 66px; }
        #s02-card { left: 80px; top: 430px; }
        #s02-ring { left: 650px; top: 450px; }
        #s02-ring .lbl { padding-bottom: 8px; }
    """, f"""
        <div class="lc-head" id="s02-head"><span id="s02-h1">Understood In</span><span class="lc-it" id="s02-h2">5 Seconds</span></div>
        {portfolio_card("s02-card", 540, 440)}
        {ring("s02-ring", 350, 18, 130)}
        {ck_row("s02-r1", "Who you are", 80, 920, 920)}
        {ck_row("s02-r2", "What you do", 80, 1036, 920)}
    """, """
          fx.typeSpan(tl, "#s02-h1", at(5.28), at(6.06));
          fx.typeSpan(tl, "#s02-h2", at(6.08), at(6.90));
          fx.blurIn(tl, "#s02-card", at(3.12));
          fx.blurIn(tl, "#s02-ring", at(3.22));
          tl.fromTo("#s02-ring-arc", { strokeDashoffset: 1 }, { strokeDashoffset: 0, duration: 3.6, ease: "none" }, at(3.33));
          fx.blurIn(tl, "#s02-r1", at(3.5), { y: 20, blur: 10 });
          fx.blurIn(tl, "#s02-r2", at(3.62), { y: 20, blur: 10 });
          fx.pop(tl, "#s02-r1-b", at(5.62), { from: 0 });
          fx.pop(tl, "#s02-r2-b", at(6.42), { from: 0 });
          tl.fromTo("#s02-ring", { boxShadow: "0 0 30px rgba(184,25,58,0.35), 0 24px 50px rgba(0,0,0,0.6)" }, { boxShadow: "0 0 90px rgba(184,25,58,0.85), 0 24px 50px rgba(0,0,0,0.6)", duration: 0.25, yoyo: true, repeat: 1, ease: "power2.out", immediateRender: false }, at(6.93));
    """, aura=(160, 360))

    # ---------------------------------------------------------------- s03 cutaway: after my reality check (hand on chin)
    cut("s03-cut-reality", 7.21, 9.02, 9.0, origin="50% 26%")

    # ---------------------------------------------------------------- s05 the best portfolios do way too much
    wins = [  # id, left, top, rot, scene-local start, duration, screen.mp4 media start
        ("w1", 60, 390, -6, 0.03, 2.95, 0.25),   # each video starts as its window pops in
        ("w2", 550, 360, 5, 0.15, 2.83, 3.97),
        ("w3", 300, 650, -2, 0.27, 2.71, 2.50),
        ("w4", 30, 760, 7, 1.73, 1.25, 5.30),
        ("w5", 580, 730, -8, 1.85, 1.13, 1.44),
    ]
    win_html = "\n".join(
        f'        <div class="bw s05-w" id="s05-{w}" data-r="{r}" data-layout-allow-overlap data-layout-allow-occlusion style="left: {x}px; top: {y}px">'
        f'<div class="bar"><i></i><i></i><i></i></div><div class="view"><video id="s05-{w}-v" class="clip" src="assets/video/screen.mp4" '
        f'data-start="{s0}" data-duration="{d}" data-media-start="{m}" data-track-index="0" muted playsinline></video></div></div>'
        for w, x, y, r, s0, d, m in wins)
    chips = [("3D Objects", 80, 1030), ("Collages", 400, 1075), ("Loud Type", 690, 1020), ("Cursor FX", 260, 960)]
    chip_html = "\n".join(f'        <div class="lc-chip s05-c" id="s05-c{i}" style="left: {x}px; top: {y}px">{t}</div>' for i, (t, x, y) in enumerate(chips))
    panel("s05-too-much", 11.27, 14.25, """
        #s05-pill { left: 230px; top: 640px; z-index: 6; font-size: 76px; padding: 10px 34px 16px; }
        .s05-c { z-index: 5; }
    """, f"""
{win_html}
{chip_html}
        <div class="lc-pill" id="s05-pill" data-layout-allow-overlap data-layout-allow-occlusion>Way Too Much</div>
    """, """
          root.querySelectorAll(".s05-w").forEach((el, i) => {
            const r = parseFloat(el.dataset.r);
            const t = i < 3 ? at(11.30 + i * 0.12) : at(13.00 + (i - 3) * 0.12);
            tl.fromTo(el, { opacity: 0, scale: 0.6, rotation: r * 2, filter: "blur(14px)" }, { opacity: 1, scale: 1, rotation: r, filter: "blur(0px)", duration: 0.5, ease: "expo.out" }, t);
            tl.to(el, { y: [-14, 12, -10, 14, -12][i], rotation: r + [2, -2, 1.5, -2, 2][i], duration: 2.2, ease: "sine.inOut" }, t + 0.5);
          });
          root.querySelectorAll(".s05-c").forEach((el, i) => {
            tl.fromTo(el, { opacity: 0, scale: 0.4, rotation: [-10, 8, -6, 10][i] }, { opacity: 1, scale: 1, rotation: [-4, 3, -3, 5][i], duration: 0.35, ease: "back.out(2)" }, at(13.05 + i * 0.08));
          });
          fx.pop(tl, "#s05-pill", at(13.29), { from: 0.3, rot0: -10, rot: -3, dur: 0.35 });
          fx.shake(tl, root.querySelectorAll(".s05-w"), at(13.64), 12);
          fx.shake(tl, "#s05-pill", at(13.66), 8);
    """, aura=(160, 420), crumb=("Chapter 01", "Study The Best"))

    # ---------------------------------------------------------------- s07 totally different: the clean portfolio
    panel("s07-different", 17.23, 20.37, f"""
        #s07-head {{ top: 250px; font-size: 66px; }}
        #s07-box {{ left: 72px; top: 400px; width: {PANEL_W}px; height: {PANEL_VH + 52}px; }}
        #s07-view {{ position: absolute; left: 0; top: 52px; width: {PANEL_W}px; height: {PANEL_VH}px; overflow: hidden; background: #f3f3f3; }}
        #s07-view video {{ position: absolute; left: 0; top: 0; width: {PANEL_W}px; height: {PANEL_VH}px; object-fit: cover; }}
        .s07-p {{ top: 1030px; display: inline-flex; align-items: center; gap: 14px; }}
        #s07-p1 {{ left: 170px; }}
        #s07-p2 {{ left: 530px; }}
    """, f"""
        <div class="lc-head" id="s07-head"><span id="s07-h1">Totally</span><span class="lc-it" id="s07-h2">Different</span></div>
        <div class="gl crim" id="s07-box"><div class="bar3"><i></i><i></i><i></i><b></b></div>
          <div id="s07-view"><video id="s07-v" class="clip" src="assets/video/screen.mp4" data-start="0" data-duration="3.14" data-media-start="7.30" data-track-index="0" muted playsinline></video></div></div>
        <div class="lc-pill s07-p" id="s07-p1">{CHECK}Fluid</div>
        <div class="lc-pill s07-p" id="s07-p2">{CHECK}Efficient</div>
    """, """
          fx.typeSpan(tl, "#s07-h1", at(17.61), at(17.95));
          fx.typeSpan(tl, "#s07-h2", at(17.96), at(18.44));
          fx.blurIn(tl, "#s07-box", at(17.26), { y: 60 });
          tl.fromTo("#s07-box", { rotationX: 14, transformPerspective: 1600 }, { rotationX: 0, duration: 0.7, ease: "expo.out" }, at(17.26));
          fx.pop(tl, "#s07-p1", at(18.71), { rot0: -10, rot: -2 });
          fx.pop(tl, "#s07-p2", at(19.52), { rot0: 10, rot: 2 });
          tl.to("#s07-box", { scale: 1.03, duration: 2.6, ease: "sine.inOut" }, at(17.8));
    """, aura=(160, 420))

    # ---------------------------------------------------------------- s08 who they were and what they did, in 5 seconds
    # the hero animates in from 11.6s of screen.mp4, holds still 12.0–13.1s, then scrolls: 11.62 + 3.33s x 0.44 ends at 13.09.
    # The panel does not push in, so the boxes stay on the text.
    y0 = 400
    vt = y0 + 52
    what = (253, round(vt + 221 * SC) - 12, 557, round((334 - 221) * SC) + 24)
    who = (545, round(vt + 397 * SC) - 10, 270, round((435 - 397) * SC) + 20)

    def box(bid, x, y, w, h):
        return (f'<rect class="lc-wire s08-box" id="{bid}" x="{x}" y="{y}" width="{w}" height="{h}" rx="14" pathLength="1" '
                f'stroke-dasharray="1" stroke-dashoffset="1" />')
    panel("s08-who-what", 20.37, 23.70, f"""
        #s08-head {{ top: 250px; font-size: 66px; }}
        #s08-box {{ left: 72px; top: {y0}px; width: {PANEL_W}px; height: {PANEL_VH + 52}px; }}
        #s08-view {{ position: absolute; left: 0; top: 52px; width: {PANEL_W}px; height: {PANEL_VH}px; overflow: hidden; background: #111; }}
        #s08-view video {{ position: absolute; left: 0; top: 0; width: {PANEL_W}px; height: {PANEL_VH}px; object-fit: cover; }}
        #s08-svg {{ position: absolute; left: 0; top: 0; width: 1080px; height: 1920px; overflow: visible; z-index: 3; }}
        #s08-ring {{ left: 860px; top: 300px; z-index: 4; }}
        #s08-ring .lbl {{ padding-bottom: 4px; }}
        .s08-tag {{ position: absolute; z-index: 4; font-size: 34px; padding: 2px 16px 6px; }}
        #s08-t1 {{ left: {who[0]}px; top: {who[1] + who[3] + 8}px; }}
        #s08-t2 {{ left: {what[0]}px; top: {what[1] - 52}px; }}
    """, f"""
        <div class="lc-head" id="s08-head"><span id="s08-h1">In</span><span class="lc-it" id="s08-h2">5 Seconds</span></div>
        <div class="gl crim" id="s08-box"><div class="bar3"><i></i><i></i><i></i><b></b></div>
          <div id="s08-view"><video id="s08-v" class="clip" src="assets/video/screen.mp4" data-start="0" data-duration="3.33" data-media-start="11.62" data-playback-rate="0.44" data-track-index="0" muted playsinline></video></div></div>
        <svg id="s08-svg" viewBox="0 0 1080 1920" data-layout-allow-overflow>
          {box("s08-b1", *who)}
          {box("s08-b2", *what)}
          <circle class="lc-node" id="s08-node" cx="{what[0] + what[2]}" cy="{what[1]}" r="11" />
        </svg>
        {ring("s08-ring", 170, 10, 64)}
        <span class="lc-tag s08-tag" id="s08-t1">Who</span>
        <span class="lc-tag s08-tag" id="s08-t2">What</span>
    """, """
          fx.typeSpan(tl, "#s08-h1", at(20.37), at(20.46));
          fx.typeSpan(tl, "#s08-h2", at(20.46), at(21.14));
          fx.blurIn(tl, "#s08-box", at(20.40), { y: 40 });
          fx.pop(tl, "#s08-ring", at(20.40), { from: 0.4 });
          tl.fromTo("#s08-ring-arc", { strokeDashoffset: 1 }, { strokeDashoffset: 0, duration: 0.7, ease: "power1.inOut" }, at(20.45));
          fx.draw(tl, "#s08-b1", at(21.88), 0.35);
          fx.pop(tl, "#s08-t1", at(21.90), { rot0: -8 });
          fx.draw(tl, "#s08-b2", at(22.87), 0.35);
          fx.pop(tl, "#s08-t2", at(22.89), { rot0: 8 });
          fx.pop(tl, "#s08-node", at(23.13), { from: 0 });
    """, aura=(160, 420))

    # ---------------------------------------------------------------- s09 cutaway: that's when it clicked (leans back, looks up)
    cut("s09-cut-clicked", 23.70, 25.62, 17.75, origin="50% 20%", s1=1.1)

    # ---------------------------------------------------------------- s10 not to make people say WOW
    stars = [(170, 520, "#f5c518", 1.0), (860, 470, "#f5f5f5", 0.8), (230, 880, "#f5f5f5", 0.7), (820, 860, "#f5c518", 0.9),
             (520, 430, "#f5c518", 0.6)]
    star_html = "\n".join(
        f'        <svg class="s10-star" style="left: {x}px; top: {y}px; width: {64 * s:.0f}px; height: {64 * s:.0f}px" viewBox="0 0 40 40">'
        f'<path d="M20 0 L24 16 L40 20 L24 24 L20 40 L16 24 L0 20 L16 16 Z" fill="{c}"/></svg>' for x, y, c, s in stars)
    panel("s10-not-wow", 25.62, 27.48, """
        #s10-head { top: 300px; font-size: 66px; }
        #s10-wow { position: absolute; left: 0; right: 0; top: 560px; text-align: center; font-family: "Inter Tight", Arial, sans-serif; font-weight: 900; font-size: 280px; letter-spacing: -0.05em; line-height: 1; color: #f5f5f5; text-shadow: 0 0 50px rgba(245,197,24,0.55), 10px 10px 0 #b8193a; }
        .s10-star { position: absolute; }
        #s10-strike { position: absolute; left: 110px; top: 690px; width: 860px; height: 22px; border-radius: 11px; background: #e0324f; box-shadow: 0 0 30px rgba(224,50,79,0.9); transform: rotate(-9deg) scaleX(0); transform-origin: 0% 50%; z-index: 3; }
    """, f"""
        <div class="lc-head" id="s10-head"><span id="s10-h1">The Goal</span><span class="lc-it" id="s10-h2">Isn't…</span></div>
{star_html}
        <div id="s10-wow" data-layout-allow-overlap>WOW</div>
        <div id="s10-strike" data-layout-allow-occlusion></div>
    """, """
          fx.typeSpan(tl, "#s10-h1, #s10-h2", at(25.64), at(26.10));
          tl.fromTo("#s10-wow", { opacity: 0, scale: 0.3, rotation: -14 }, { opacity: 1, scale: 1, rotation: 0, duration: 0.45, ease: "back.out(2.6)" }, at(26.20));
          tl.to("#s10-wow", { y: -18, duration: 0.15, ease: "sine.inOut", yoyo: true, repeat: 3 }, at(26.22));
          tl.fromTo(".s10-star", { opacity: 0, scale: 0.2, rotation: 0 }, { opacity: 1, scale: 1, rotation: 90, duration: 0.4, ease: "back.out(2)", stagger: 0.05 }, at(26.25));
          tl.to(".s10-star", { rotation: 200, duration: 0.6, ease: "none" }, at(26.65));
          // "wow": struck out, drained of colour, stars fall
          tl.fromTo("#s10-strike", { scaleX: 0, rotation: -9 }, { scaleX: 1, rotation: -9, duration: 0.2, ease: "power3.out", immediateRender: false }, at(26.84));
          tl.to("#s10-wow", { color: "#5a5a5a", textShadow: "0 0 0px rgba(245,197,24,0), 10px 10px 0 #3a1219", duration: 0.25, ease: "power2.out" }, at(26.92));
          fx.shake(tl, "#s10-wow", at(26.92), 14);
          tl.to(".s10-star", { y: 260, opacity: 0, rotation: 320, duration: 0.5, ease: "power2.in", stagger: 0.04 }, at(26.95));
    """, aura=(160, 420))

    # ---------------------------------------------------------------- s11 make yourself understood
    panel("s11-understood", 27.48, 29.40, """
        #s11-head { top: 250px; font-size: 66px; }
        #s11-card { left: 160px; top: 420px; }
        #s11-ring { left: 800px; top: 380px; z-index: 3; }
        #s11-ring .lbl { padding-bottom: 4px; }
    """, f"""
        <div class="lc-head" id="s11-head"><span id="s11-h1">Make Yourself</span><span class="lc-it" id="s11-h2">Understood</span></div>
        {portfolio_card("s11-card", 760, 440)}
        {ring("s11-ring", 170, 10, 64)}
        {ck_row("s11-r1", "Who you are", 160, 920, 760)}
        {ck_row("s11-r2", "What you do", 160, 1036, 760)}
    """, """
          fx.typeSpan(tl, "#s11-h1", at(27.70), at(28.44));
          fx.typeSpan(tl, "#s11-h2", at(28.49), at(29.08));
          fx.blurIn(tl, "#s11-card", at(27.50));
          fx.blurIn(tl, "#s11-r1", at(27.62), { y: 20, blur: 10 });
          fx.blurIn(tl, "#s11-r2", at(27.74), { y: 20, blur: 10 });
          fx.pop(tl, "#s11-r1-b", at(27.95), { from: 0 });
          fx.pop(tl, "#s11-r2-b", at(28.20), { from: 0 });
          fx.pop(tl, "#s11-ring", at(28.40), { from: 0.4 });
          tl.fromTo("#s11-ring-arc", { strokeDashoffset: 1 }, { strokeDashoffset: 0, duration: 0.45, ease: "power2.out" }, at(28.45));
          tl.fromTo("#s11-card", { boxShadow: "0 0 30px rgba(255,255,255,0.07), 0 40px 90px rgba(0,0,0,0.7)" }, { boxShadow: "0 0 110px rgba(184,25,58,0.85), 0 40px 90px rgba(0,0,0,0.7)", duration: 0.3, yoyo: true, repeat: 1, ease: "power2.out", immediateRender: false }, at(28.49));
    """, aura=(160, 380))

    # ---------------------------------------------------------------- s13 rebuilt on that logic: a wireframe assembles
    panel("s13-logic", 31.45, 32.84, """
        #s13-frame { position: absolute; left: 110px; top: 380px; width: 860px; height: 640px; border-radius: 24px; border: 3px dashed rgba(255,255,255,0.35); }
        .s13-b { position: absolute; }
        #s13-b1 { left: 160px; top: 440px; font-family: "Inter Tight", Arial, sans-serif; font-weight: 800; font-size: 76px; letter-spacing: -0.04em; color: #f5f5f5; line-height: 1; }
        #s13-b2 { left: 160px; top: 540px; font-family: "Instrument Serif", Georgia, serif; font-style: italic; font-size: 54px; color: #bdbbb8; line-height: 1; }
        .s13-w { top: 640px; width: 240px; height: 200px; border-radius: 14px; background: linear-gradient(180deg, #2c2b2d, #1a191b); border: 2px solid rgba(255,255,255,0.14); }
        #s13-b6 { left: 160px; top: 890px; padding: 12px 34px 16px; border-radius: 36px; background: #99122b; font-family: "Inter Tight", Arial, sans-serif; font-weight: 800; font-size: 40px; color: #fff; box-shadow: 0 0 30px rgba(184,25,58,0.5); }
        #s13-ring { left: 790px; top: 330px; z-index: 3; }
        #s13-ring .lbl { padding-bottom: 4px; }
    """, f"""
        <div id="s13-frame"></div>
        <div class="s13-b" id="s13-b1">Who I am</div>
        <div class="s13-b" id="s13-b2">What I do</div>
        <div class="s13-b s13-w" id="s13-b3" style="left: 160px"></div>
        <div class="s13-b s13-w" id="s13-b4" style="left: 420px"></div>
        <div class="s13-b s13-w" id="s13-b5" style="left: 680px"></div>
        <div class="s13-b" id="s13-b6">Contact</div>
        {ring("s13-ring", 170, 10, 64)}
    """, """
          tl.fromTo("#s13-frame", { opacity: 0, scale: 0.94 }, { opacity: 1, scale: 1, duration: 0.3, ease: "power3.out" }, at(31.47));
          root.querySelectorAll(".s13-b").forEach((el, i) => {
            tl.fromTo(el, { opacity: 0, y: -40, filter: "blur(8px)" }, { opacity: 1, y: 0, filter: "blur(0px)", duration: 0.28, ease: "back.out(1.6)" }, at(31.55 + i * 0.1));
          });
          fx.pop(tl, "#s13-ring", at(32.15), { from: 0.4 });
          tl.fromTo("#s13-ring-arc", { strokeDashoffset: 1 }, { strokeDashoffset: 0, duration: 0.4, ease: "power2.out" }, at(32.21));
    """, aura=(160, 400), crumb=("Chapter 03", "Rebuild"))

    # ---------------------------------------------------------------- s14 CTA: follow me
    icons = [
        '<svg viewBox="0 0 54 54"><rect x="3" y="3" width="48" height="48" rx="12" fill="#c2304b"/><circle cx="24" cy="24" r="9.5" stroke="#fff" stroke-width="4" fill="none"/><path d="M31.5 31.5 L40 40" stroke="#fff" stroke-width="4.6" stroke-linecap="round"/></svg>',
        '<svg viewBox="0 0 54 54"><rect x="3" y="3" width="48" height="48" rx="12" fill="#f5f5f5"/><rect x="11" y="13" width="32" height="28" rx="4" fill="none" stroke="#99122b" stroke-width="3"/><path d="M11 20 H43" stroke="#99122b" stroke-width="3"/><path d="M16 27 H32 M16 33 H26" stroke="#99122b" stroke-width="3.4" stroke-linecap="round"/></svg>',
        '<svg viewBox="0 0 54 54"><rect x="3" y="3" width="48" height="48" rx="12" fill="#e0902a"/><rect x="13" y="30" width="12" height="11" rx="2" fill="#fff"/><rect x="29" y="30" width="12" height="11" rx="2" fill="#fff"/><rect x="21" y="16" width="12" height="11" rx="2" fill="#fff"/></svg>',
    ]
    names = ["Study The Best", "Cofolio", "Rebuilt From Scratch"]
    tiles = "".join(
        f'<div class="lc-tile s14-t" style="left: {80 + i * 320}px; top: 900px"><span class="ico">{icons[i]}</span><span class="rule"></span>'
        f'<span class="n">0{i + 1}</span><span class="nm">{names[i]}</span></div>' for i in range(3))
    panel("s14-cta", 32.84, 38.00, """
        #s14-hub2 .l1 { visibility: hidden; }
        .s14-t { width: 280px; height: 220px; }
        .s14-t .ico { display: block; }
        .s14-t .ico svg { display: block; width: 100%; height: 100%; }
        .s14-t .nm { margin-top: 4px; font-weight: 800; font-size: 28px; letter-spacing: -0.02em; line-height: 1.05; text-align: center; padding: 0 12px; }
        #s14-btn { position: absolute; left: 240px; top: 620px; width: 600px; height: 150px; border-radius: 75px; background: #99122b; border: 3px solid rgba(255,255,255,0.25); box-shadow: 0 0 50px rgba(184,25,58,0.55), 0 30px 70px rgba(0,0,0,0.6); display: flex; align-items: center; justify-content: center; gap: 20px; font-family: "Inter Tight", Arial, sans-serif; font-weight: 800; font-size: 64px; letter-spacing: -0.03em; color: #fff; }
        #s14-done { position: absolute; left: 240px; top: 620px; width: 600px; height: 150px; border-radius: 75px; background: #2a292b; border: 3px solid rgba(255,255,255,0.18); display: flex; align-items: center; justify-content: center; gap: 16px; font-family: "Inter Tight", Arial, sans-serif; font-weight: 800; font-size: 58px; color: #d8d6d3; opacity: 0; }
        #s14-ripple { position: absolute; left: 600px; top: 620px; width: 220px; height: 220px; border-radius: 50%; background: rgba(255,90,110,0.45); opacity: 0; }
        #s14-cursor { position: absolute; left: 660px; top: 720px; width: 70px; height: 86px; overflow: visible; z-index: 6; }
    """, f"""
        <div class="lc-hub" id="s14-hub"><span class="l1" id="s14-a1">Web Designers</span><span class="l2" id="s14-a2">Follow Me</span></div>
        <div class="lc-hub" id="s14-hub2"><span class="l1">Web Designers</span><span class="l2"><span id="s14-b1">I'll Show You</span> <span class="lc-it" id="s14-b2">What Worked</span></span></div>
        {tiles}
        <div id="s14-done" data-layout-allow-overlap><svg width="52" height="52" viewBox="0 0 52 52"><path d="M10 27 L21 38 L43 13" fill="none" stroke="#d8d6d3" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/></svg>Following</div>
        <div id="s14-btn"><svg width="54" height="54" viewBox="0 0 54 54"><path d="M27 8 V46 M8 27 H46" stroke="#fff" stroke-width="8" stroke-linecap="round"/></svg>Follow</div>
        <div id="s14-ripple"></div>
        <svg id="s14-cursor" viewBox="0 0 70 86"><path d="M6 4 L6 66 L22 52 L33 78 L45 73 L34 47 L56 47 Z" fill="#ffffff" stroke="#111" stroke-width="4" stroke-linejoin="round"/></svg>
    """, """
          fx.typeSpan(tl, "#s14-a1", at(33.40), at(34.22));
          fx.typeSpan(tl, "#s14-a2", at(34.53), at(35.33));
          fx.pop(tl, "#s14-btn", at(33.0), { from: 0.3, dur: 0.45, ease: "back.out(2.2)" });
          tl.fromTo("#s14-cursor", { opacity: 0, x: 260, y: 300 }, { opacity: 1, x: 0, y: 0, duration: 0.45, ease: "power3.out" }, at(34.0));
          // "follow": the button gets clicked
          tl.to("#s14-cursor", { scale: 0.82, duration: 0.07, ease: "power2.in" }, at(34.60));
          tl.to("#s14-cursor", { scale: 1, duration: 0.18, ease: "back.out(2)" }, at(34.67));
          tl.to("#s14-btn", { scale: 0.93, duration: 0.07, ease: "power2.in" }, at(34.60));
          tl.fromTo("#s14-ripple", { opacity: 1, scale: 0.1 }, { opacity: 0, scale: 1.6, duration: 0.55, ease: "power2.out", immediateRender: false }, at(34.60));
          tl.to("#s14-btn", { opacity: 0, duration: 0.14, ease: "power1.out" }, at(34.68));
          tl.fromTo("#s14-done", { opacity: 0, scale: 0.93 }, { opacity: 1, scale: 1, duration: 0.4, ease: "back.out(2.6)", immediateRender: false }, at(34.68));
          tl.to("#s14-cursor", { x: 140, y: 160, opacity: 0, duration: 0.5, ease: "power2.in" }, at(35.2));
          // "and I'll show you what worked": line 2 swaps, the three chapters come back
          tl.to("#s14-a2", { opacity: 0, filter: "blur(10px)", duration: 0.2, ease: "power2.in" }, at(35.62));
          fx.typeSpan(tl, "#s14-b1, #s14-b2", at(35.98), at(36.92), { hidden: true });
          root.querySelectorAll(".s14-t").forEach((el, i) => {
            tl.fromTo(el, { opacity: 0, y: 50, filter: "blur(12px)" }, { opacity: 1, y: 0, filter: "blur(0px)", duration: 0.45, ease: "expo.out" }, at(35.62 + i * 0.12));
            tl.to(el, { y: [-12, 10, -10][i], duration: 1.6, ease: "sine.inOut" }, at(36.2));
          });
    """, aura=(160, 360))

    print("scenes written")


if __name__ == "__main__":
    main()
