#!/usr/bin/env python3
"""Generate the listicle hub scenes (s01, s04, s06, s12) from one template.

The hub is the film's recurring title card (STYLE.md §1): the title, three chapter tiles floating around the crimson
"5 Seconds" ball, and on each return one tile flying to the centre as the hero while its label types in.
All times are GLOBAL voice-over seconds (transcript.json).
    python3 tools/gen_hubs.py
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONTS = (ROOT / "tools/fonts.css.snippet").read_text()

ICONS = [
    # 01 study the best: magnifier
    '<svg viewBox="0 0 54 54"><rect x="3" y="3" width="48" height="48" rx="12" fill="#c2304b"/><circle cx="24" cy="24" r="9.5" stroke="#fff" stroke-width="4" fill="none"/><path d="M31.5 31.5 L40 40" stroke="#fff" stroke-width="4.6" stroke-linecap="round"/></svg>',
    # 02 cofolio: a clean, readable page (no brand logo is known, so a generic browser glyph)
    '<svg viewBox="0 0 54 54"><rect x="3" y="3" width="48" height="48" rx="12" fill="#f5f5f5"/><rect x="11" y="13" width="32" height="28" rx="4" fill="none" stroke="#99122b" stroke-width="3"/><path d="M11 20 H43" stroke="#99122b" stroke-width="3"/><path d="M16 27 H32 M16 33 H26" stroke="#99122b" stroke-width="3.4" stroke-linecap="round"/></svg>',
    # 03 rebuilt from scratch: stacked blocks
    '<svg viewBox="0 0 54 54"><rect x="3" y="3" width="48" height="48" rx="12" fill="#e0902a"/><rect x="13" y="30" width="12" height="11" rx="2" fill="#fff"/><rect x="29" y="30" width="12" height="11" rx="2" fill="#fff"/><rect x="21" y="16" width="12" height="11" rx="2" fill="#fff"/></svg>',
]
NAMES = ["Study The Best", "Cofolio", "Rebuilt From Scratch"]
# cloud positions (left, top) of the small tiles; the ball sits at 425,600 (230x230)
CLOUD = [(120, 500), (770, 470), (445, 900)]
ROT0 = [(-8, -5), (6, 4), (5, 3)]
DRIFT = [-16, 12, -10]
HERO = (350, 600)  # hero tile 380x336


def tile_html(p, i):
    return (
        f'<div class="lc-tile {p}-cloud" id="{p}-t{i}" style="left: {CLOUD[i][0]}px; top: {CLOUD[i][1]}px">'
        f'<span class="ico">{ICONS[i]}</span><span class="rule"></span><span class="n">0{i + 1}</span><span class="lab"></span></div>'
    )


def scene(sid, t0, t1, focus=None, title=(0.0, 0.0, 0.0, 0.0), label=None, cloud=True, extra_html="", extra_js="",
          ball=True):
    """title = (l1 typing start, end, l2 typing start, end); label = (typing start, end) for the hero's name."""
    p = sid.split("-")[0]
    hero = hero_js = ""
    if focus is not None:
        hx, hy = HERO
        cx, cy = CLOUD[focus]
        lt0, lt1 = label
        fly = max(t0, lt0 - 0.7)
        hero = (
            f'<div class="lc-tile hero" id="{p}-hero" style="left: {hx}px; top: {hy}px">'
            f'<span class="ico">{ICONS[focus]}</span><span class="rule"></span><span class="n">0{focus + 1}</span>'
            f'<span class="name" id="{p}-name">{NAMES[focus]}</span></div>'
        )
        dx = cx + 95 - (hx + 190)
        dy = cy + 84 - (hy + 168)
        hero_js = f"""
          tl.fromTo("#{p}-hero", {{ x: {dx}, y: {dy}, scale: 0.5, opacity: 0.9 }}, {{ x: 0, y: 0, scale: 1, opacity: 1, duration: 0.6, ease: "expo.out" }}, at({fly:.2f}));
          fx.typeSpan(tl, "#{p}-name", at({lt0:.2f}), at({lt1:.2f}));
          tl.to("#{p}-hero", {{ y: -12, duration: 1.4, ease: "sine.inOut", yoyo: true, repeat: 1 }}, at({fly + 0.6:.2f}));"""
        if cloud:
            hero_js += f"""
          tl.to(".{p}-cloud", {{ opacity: 0, filter: "blur(14px)", scale: 0.8, duration: 0.4, ease: "power2.in", stagger: 0.04 }}, at({fly:.2f}));
          tl.to("#{p}-ball", {{ opacity: 0, scale: 0.6, filter: "blur(10px)", duration: 0.4, ease: "power2.in" }}, at({fly:.2f}));"""
    tiles = "\n        ".join(tile_html(p, i) for i in range(3) if i != focus) if cloud else ""
    ball_html = f'<div class="lc-ball" id="{p}-ball" style="left: 425px; top: 600px">5 Seconds</div>' if ball and cloud else ""
    cloud_js = ""
    if cloud:
        cloud_js = f"""
          root.querySelectorAll(".{p}-cloud").forEach((el) => {{
            const i = parseInt(el.id.slice(-1), 10);
            const r0 = {[r[0] for r in ROT0]}[i], r1 = {[r[1] for r in ROT0]}[i], dy = {DRIFT}[i];
            tl.fromTo(el, {{ opacity: 0, scale: 0.6, filter: "blur(14px)", rotation: r0 }}, {{ opacity: 1, scale: 1, filter: "blur(0px)", rotation: r1, duration: 0.5, ease: "expo.out" }}, at({{CLOUD_IN}} + i * 0.08));
            tl.to(el, {{ y: dy, duration: {max(1.0, t1 - t0 - 0.6):.2f}, ease: "sine.inOut" }}, at({{CLOUD_IN}} + 0.5));
          }});"""
        if ball:
            cloud_js += f"""
          tl.fromTo("#{p}-ball", {{ scale: 0.3, opacity: 0 }}, {{ scale: 1, opacity: 1, duration: 0.55, ease: "back.out(1.8)" }}, at({{CLOUD_IN}} + 0.1));"""
    a0, a1, b0, b1 = title
    return f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <!-- Generated by tools/gen_hubs.py: edit the generator, not this file. -->
    <template id="{sid}-template">
      <link rel="stylesheet" href="assets/css/components.css" />
      <link rel="stylesheet" href="assets/css/house.css" />
      <style>
{FONTS}        #{p}-root .lc-tile .ico {{ display: block; }}
        #{p}-root .lc-tile .ico svg {{ display: block; width: 100%; height: 100%; }}
        #{p}-root .lc-tile.hero .name {{ max-width: 330px; }}
        #{p}-l1 {{ font-size: 80px; }}
      </style>
      <div id="{p}-root" class="scene-root" data-composition-id="{sid}" data-width="1080" data-height="1920">
        <div class="lc-bg"><div class="lc-grid" data-layout-allow-overflow></div><div class="lc-aura" style="left: 160px; top: 340px" data-layout-allow-overflow></div><div class="lc-vignette"></div></div>
        <div class="lc-hub" id="{p}-hub">
          <span class="l1" id="{p}-l1">Forget The Animations</span>
          <span class="l2" id="{p}-l2">If You Want Real Contracts</span>
        </div>
        {extra_html}
        {tiles}
        {ball_html}
        {hero}
      </div>
      <script>
        (function () {{
          const T0 = {t0};
          const at = (t) => Math.max(0, t - T0);
          const tl = gsap.timeline({{ paused: true }});
          const root = document.getElementById("{p}-root");
          fx.ambient(tl, root, {t1 - t0:.2f});
          fx.typeSpan(tl, "#{p}-l1", at({a0}), at({a1}));
          fx.typeSpan(tl, "#{p}-l2", at({b0}), at({b1}));
          {cloud_js}
          {hero_js}
          {extra_js}
          window.__timelines["{sid}"] = tl;
        }})();
      </script>
    </template>
  </body>
</html>
"""


# the hook: the user's clip of over-animated portfolio sites (assets/video/intro.mp4, the 16:9 band of their upload),
# played at 2x in a browser window under "Forget the animations", struck out as the word ends, then collapsed
INTRO_HTML = """
        <div class="gl crim" id="s01-box" data-layout-allow-overflow><div class="bar3"><i></i><i></i><i></i><b></b></div>
          <div id="s01-view"><video id="s01-v" class="clip" src="assets/video/intro.mp4" data-start="0" data-duration="1.7" data-media-start="0" data-playback-rate="2" data-track-index="0" muted playsinline></video></div></div>
        <div id="s01-strike" data-layout-allow-occlusion></div>"""
INTRO_CSS = """
        #s01-box { left: 72px; top: 400px; width: 936px; height: 579px; }
        #s01-view { position: absolute; left: 0; top: 52px; width: 936px; height: 527px; overflow: hidden; background: #f3f3f3; }
        #s01-view video { position: absolute; left: 0; top: 0; width: 936px; height: 527px; object-fit: cover; }
        #s01-strike { position: absolute; left: 60px; top: 680px; width: 960px; height: 18px; border-radius: 9px; background: #e0324f; box-shadow: 0 0 26px rgba(224,50,79,0.85); transform: rotate(-12deg) scaleX(0); transform-origin: 0% 50%; z-index: 3; }"""
INTRO_JS = """
          // the clip is on screen from the first frame (the hook), settling in...
          tl.fromTo("#s01-box", { scale: 1.08, rotationX: 10, transformPerspective: 1600, filter: "blur(6px)" }, { scale: 1, rotationX: 0, filter: "blur(0px)", duration: 0.35, ease: "expo.out" }, 0);
          tl.to("#s01-box", { scale: 1.03, duration: 0.7, ease: "sine.inOut" }, 0.38);
          // ...struck out as "animations" ends, then it collapses into the hub
          tl.fromTo("#s01-strike", { scaleX: 0, rotation: -12 }, { scaleX: 1, rotation: -12, duration: 0.22, ease: "power3.out", immediateRender: false }, 1.08);
          fx.shake(tl, "#s01-box", 1.16, 10);
          tl.to("#s01-box", { opacity: 0, scale: 0.85, filter: "blur(18px)", duration: 0.32, ease: "power2.in" }, 1.36);
          tl.to("#s01-strike", { opacity: 0, duration: 0.25, ease: "power2.in" }, 1.42);"""


def main():
    out = {
        # hook: the title types as spoken over the user's clip, which is struck out; then the tile cloud and ball arrive
        "s01-hub-hook": scene(
            "s01-hub-hook", 0.0, 3.08, title=(0.02, 1.30, 1.60, 2.94), extra_html=INTRO_HTML,
            extra_js=INTRO_JS,
        ).replace("{CLOUD_IN}", "1.62").replace("        #s01-l1 { font-size: 80px; }", "        #s01-l1 { font-size: 80px; }" + INTRO_CSS),
        # "I started studying the best" — hero 01
        "s04-hub-01": scene("s04-hub-01", 9.02, 11.27, focus=0, title=(9.04, 9.30, 9.30, 9.62), label=(10.15, 11.20))
        .replace("{CLOUD_IN}", "9.04"),
        # "But then, I found Cofolio" — hero 02
        "s06-hub-02": scene("s06-hub-02", 14.25, 17.23, focus=1, title=(14.27, 14.55, 14.55, 14.95), label=(15.60, 16.20))
        .replace("{CLOUD_IN}", "14.27"),
        # "So I rebuilt everything from scratch" — hero 03 (no time for the cloud)
        "s12-hub-03": scene("s12-hub-03", 29.40, 31.45, focus=2, title=(29.42, 29.62, 29.62, 29.85), label=(29.80, 31.40),
                            cloud=False),
    }
    for sid, html in out.items():
        (ROOT / f"compositions/{sid}.html").write_text(html)
        print("wrote", sid)


if __name__ == "__main__":
    main()
