#!/usr/bin/env python3
"""Generate the story scenes (everything except the hub cards, which tools/gen_hubs.py writes).

Each scene: listicle-crimson background, optional breadcrumb, headline, and its own graphic. All times are GLOBAL
voice-over seconds (transcript.json); `at(t)` converts to scene-local time.
    python3 tools/gen_scenes.py
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONTS = (ROOT / "tools/fonts.css.snippet").read_text()


def panel(sid, t0, t1, css, body, js, aura=(160, 360), crumb=None):
    p = sid.split("-")[0]
    crumb_html = ""
    crumb_js = ""
    if crumb:
        crumb_html = (f'<div class="lc-crumb" id="{p}-crumb"><i class="tl"></i><i class="tr"></i><i class="bl"></i><i class="br"></i>'
                      f'<span class="k">{crumb[0]}</span><span class="v">{crumb[1]}</span></div>')
        crumb_js = f'tl.fromTo("#{p}-crumb", {{ opacity: 0, y: -18 }}, {{ opacity: 1, y: 0, duration: 0.35, ease: "power3.out" }}, 0.03);'
    html = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <!-- Generated by tools/gen_scenes.py: edit the generator, not this file. -->
    <template id="{sid}-template">
      <link rel="stylesheet" href="assets/css/components.css" />
      <link rel="stylesheet" href="assets/css/house.css" />
      <style>
{FONTS}{css}
      </style>
      <div id="{p}-root" class="scene-root" data-composition-id="{sid}" data-width="1080" data-height="1920">
        <div class="lc-bg"><div class="lc-grid" data-layout-allow-overflow></div><div class="lc-aura" style="left: {aura[0]}px; top: {aura[1]}px" data-layout-allow-overflow></div><div class="lc-vignette"></div></div>
        {crumb_html}
{body}
      </div>
      <script>
        (function () {{
          const T0 = {t0};
          const at = (t) => Math.max(0, t - T0);
          const tl = gsap.timeline({{ paused: true }});
          const root = document.getElementById("{p}-root");
          fx.ambient(tl, root, {t1 - t0:.2f});
          {crumb_js}
{js}
          window.__timelines["{sid}"] = tl;
        }})();
      </script>
    </template>
  </body>
</html>
"""
    (ROOT / f"compositions/{sid}.html").write_text(html)


def cut(sid, t0, t1, media_start, origin="50% 30%", s0=1.0, s1=1.12, y1=0):
    p = sid.split("-")[0]
    html = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <!-- Generated by tools/gen_scenes.py. Full-screen cutaway of the user's footage. -->
    <template id="{sid}-template">
      <style>
        #{p}-root {{ position: absolute; inset: 0; overflow: hidden; background: #0b0b0b; }}
        #{p}-cam {{ position: absolute; inset: 0; transform-origin: {origin}; }}
        #{p}-cam video {{ position: absolute; left: 0; top: 0; width: 1080px; height: 1920px; object-fit: cover; }}
        #{p}-shade {{ position: absolute; inset: 0; background: radial-gradient(ellipse 80% 60% at 50% 32%, rgba(0,0,0,0) 0%, rgba(0,0,0,0.55) 100%), linear-gradient(180deg, rgba(0,0,0,0) 45%, rgba(0,0,0,0.5) 100%); }}
      </style>
      <div id="{p}-root" data-composition-id="{sid}" data-width="1080" data-height="1920">
        <div id="{p}-cam">
          <video id="{p}-v" class="clip" src="assets/video/people.mp4" data-start="0" data-duration="{t1 - t0:.2f}" data-media-start="{media_start}" data-track-index="0" muted playsinline></video>
        </div>
        <div id="{p}-shade"></div>
      </div>
      <script>
        (function () {{
          const tl = gsap.timeline({{ paused: true }});
          tl.fromTo("#{p}-cam", {{ scale: {s0 + 0.12}, filter: "blur(10px)" }}, {{ scale: {s0}, filter: "blur(0px)", duration: 0.3, ease: "power3.out" }}, 0);
          tl.to("#{p}-cam", {{ scale: {s1}, y: {y1}, duration: {t1 - t0 - 0.3:.2f}, ease: "sine.inOut" }}, 0.3);
          window.__timelines["{sid}"] = tl;
        }})();
      </script>
    </template>
  </body>
</html>
"""
    (ROOT / f"compositions/{sid}.html").write_text(html)


CH = {1: ("Chapter 01", "Ready-Made Portfolio"), 2: ("Chapter 02", "Mass Outreach"), 3: ("Chapter 03", "The $350 Client"),
      4: ("Chapter 04", "Study The Best")}


def main():
    # ---------------------------------------------------------------- s03 views up, bank flat
    panel("s03-views-bank", 9.92, 15.00, """
        #s03-head { top: 312px; }
        .s03-p { width: 440px; height: 400px; top: 470px; }
        #s03-a { left: 80px; }
        #s03-b { left: 560px; }
        .s03-p .big-num { position: absolute; left: 34px; top: 92px; font-size: 92px; }
        .s03-p svg { position: absolute; left: 34px; top: 230px; width: 372px; height: 130px; overflow: visible; }
        #s03-up { position: absolute; right: 30px; top: 24px; font-size: 24px; padding: 6px 16px; }
        #s03-vs { position: absolute; left: 505px; top: 640px; width: 70px; height: 70px; border-radius: 35px; background: #0b0b0b; border: 2px solid rgba(255,255,255,0.2); z-index: 2; display: flex; align-items: center; justify-content: center; font-family: "Instrument Serif", Georgia, serif; font-style: italic; font-size: 40px; color: #f5f5f5; }
    """, """
        <div class="lc-head" id="s03-head"><span id="s03-h1">Views Up,</span><span class="lc-it" id="s03-h2">Bank Flat</span></div>
        <div class="gl s03-p" id="s03-a"><span class="hd">Social media</span><span class="lc-tag" id="s03-up">Taking off</span>
          <span class="big-num" id="s03-g">↑</span>
          <svg viewBox="0 0 372 130"><path class="lc-wire" id="s03-l1" d="M0 122 C 80 118, 120 100, 170 84 S 280 40, 372 6" pathLength="1" stroke-dasharray="1" stroke-dashoffset="1" /></svg></div>
        <div id="s03-vs">vs</div>
        <div class="gl s03-p" id="s03-b"><span class="hd">Bank account</span>
          <span class="big-num" id="s03-bal">$0</span>
          <svg viewBox="0 0 372 130"><path d="M0 110 H372" stroke="rgba(255,255,255,0.18)" stroke-width="3" stroke-dasharray="9 9" fill="none" /><path class="lc-wire" id="s03-l2" d="M0 110 H372" pathLength="1" stroke-dasharray="1" stroke-dashoffset="1" /></svg></div>
    """, """
          fx.typeSpan(tl, "#s03-h1", at(11.18), at(12.3));
          fx.typeSpan(tl, "#s03-h2", at(12.89), at(14.4));
          fx.blurIn(tl, "#s03-a", at(11.1));
          fx.draw(tl, "#s03-l1", at(11.5), 0.9);
          fx.pop(tl, "#s03-up", at(12.0));
          fx.pop(tl, "#s03-vs", at(12.85), { from: 0.3 });
          fx.blurIn(tl, "#s03-b", at(13.45));
          fx.draw(tl, "#s03-l2", at(13.9), 0.8);
          fx.shake(tl, "#s03-bal", at(14.55), 12);
          tl.to("#s03-bal", { color: "#ff4d63", duration: 0.15, ease: "none" }, at(14.55));
          tl.to("#s03-a", { opacity: 0.5, filter: "blur(2px)", duration: 0.4, ease: "power1.out" }, at(13.5));
    """, crumb=CH[1])

    # ---------------------------------------------------------------- s04 cutaway: obsessed (shot B: to camera → chin)
    cut("s04-cut-obsessed", 15.00, 20.15, 7.2, origin="50% 26%", s0=1.0, s1=1.14, y1=30)

    # ---------------------------------------------------------------- s05 my problem: no portfolio
    panel("s05-no-portfolio", 20.15, 23.42, """
        #s05-head { top: 220px; font-size: 76px; }
        #s05-card { left: 190px; top: 470px; width: 700px; height: 520px; }
        .s05-ph { position: absolute; border: 3px dashed rgba(255,255,255,0.22); border-radius: 14px; }
        #s05-q { position: absolute; left: 0; right: 0; top: 150px; text-align: center; font-family: "Instrument Serif", Georgia, serif; font-style: italic; font-size: 260px; line-height: 1; color: #e0324f; text-shadow: 0 0 50px rgba(184,25,58,0.7); }
        #s05-lbl { position: absolute; left: 0; right: 0; bottom: 34px; text-align: center; font-weight: 700; font-size: 30px; color: #8f8d8a; }
    """, """
        <div class="lc-head" id="s05-head"><span id="s05-h1">My Problem:</span><span class="lc-it" id="s05-h2">No Portfolio</span></div>
        <div class="gl" id="s05-card"><div class="bar3"><i></i><i></i><i></i><b></b></div>
          <span class="s05-ph" style="left: 40px; top: 90px; width: 380px; height: 60px"></span>
          <span class="s05-ph" style="left: 40px; top: 170px; width: 300px; height: 40px"></span>
          <span class="s05-ph" style="left: 460px; top: 90px; width: 200px; height: 300px"></span>
          <span class="s05-ph" style="left: 40px; top: 300px; width: 380px; height: 90px"></span>
          <div id="s05-q">?</div><div id="s05-lbl">portfolio.html: empty</div></div>
    """, """
          fx.typeSpan(tl, "#s05-h1", at(20.4), at(21.9));
          fx.typeSpan(tl, "#s05-h2", at(22.1), at(23.2));
          fx.blurIn(tl, "#s05-card", at(20.25));
          tl.fromTo(root.querySelectorAll(".s05-ph"), { opacity: 0 }, { opacity: 1, duration: 0.3, stagger: 0.08, ease: "power1.out" }, at(20.6));
          fx.pop(tl, "#s05-q", at(22.74), { from: 0.2, dur: 0.5 });
          fx.blurIn(tl, "#s05-lbl", at(22.9), { y: 10, blur: 6 });
    """, crumb=None)

    # ---------------------------------------------------------------- s07 outreach wires
    rows, cols = 4, 3
    tiles, wires = [], []
    for r in range(rows):
        for c in range(cols):
            x, y = 640 + c * 128, 430 + r * 112
            tiles.append(f'<div class="s07-co" style="left: {x}px; top: {y}px"><i></i><b></b></div>')
            wires.append(f'<path class="lc-wire s07-w" d="M 400 650 C 500 650, {x - 60} {y + 40}, {x} {y + 40}" pathLength="1" stroke-dasharray="1" stroke-dashoffset="1" />')
    panel("s07-outreach", 28.05, 32.72, """
        #s07-tpl { left: 70px; top: 520px; width: 330px; height: 260px; }
        #s07-tpl .blk { position: absolute; border-radius: 8px; background: rgba(255,255,255,0.18); }
        #s07-tplname { position: absolute; left: 70px; top: 800px; width: 330px; text-align: center; font-family: "Inter Tight", Arial, sans-serif; font-weight: 800; font-size: 34px; color: #f5f5f5; }
        .s07-co { position: absolute; width: 108px; height: 90px; border-radius: 14px; background: linear-gradient(180deg,#232325,#111113); border: 2px solid rgba(255,255,255,0.16); box-shadow: 0 0 16px rgba(255,255,255,0.06); }
        .s07-co i { position: absolute; left: 36px; top: 14px; width: 36px; height: 30px; border-radius: 6px; background: rgba(255,255,255,0.3); }
        .s07-co b { position: absolute; left: 22px; top: 58px; width: 64px; height: 10px; border-radius: 5px; background: rgba(255,255,255,0.2); filter: blur(2px); }
        #s07-svg { position: absolute; left: 0; top: 0; width: 1080px; height: 1920px; overflow: visible; }
        #s07-mail { position: absolute; left: 80px; top: 880px; }
        #s07-dm { position: absolute; left: 250px; top: 880px; }
    """, f"""
        <svg id="s07-svg" viewBox="0 0 1080 1920" data-layout-allow-overflow>{''.join(wires)}</svg>
        <div class="gl" id="s07-tpl"><div class="bar3"><i></i><i></i><i></i><b style="width: 140px"></b></div>
          <span class="blk" style="left: 24px; top: 76px; width: 200px; height: 26px"></span>
          <span class="blk" style="left: 24px; top: 114px; width: 150px; height: 26px"></span>
          <span class="blk" style="left: 24px; top: 170px; width: 120px; height: 44px; border-radius: 22px; background: #99122b"></span>
          <span class="blk" style="left: 236px; top: 76px; width: 70px; height: 140px"></span></div>
        <div id="s07-tplname">Generic template</div>
        {''.join(tiles)}
        <span class="lc-chip" id="s07-mail">Emails</span>
        <span class="lc-chip" id="s07-dm">DMs</span>
    """, """
          fx.blurIn(tl, "#s07-tpl", at(28.15));
          fx.typeSpan(tl, "#s07-tplname", at(28.21), at(29.2));
          fx.pop(tl, "#s07-mail", at(29.73));
          fx.pop(tl, "#s07-dm", at(30.79));
          tl.fromTo(root.querySelectorAll(".s07-co"), { opacity: 0, scale: 0.4 }, { opacity: 1, scale: 1, duration: 0.3, ease: "back.out(2)", stagger: 0.03 }, at(31.3));
          fx.draw(tl, root.querySelectorAll(".s07-w"), at(31.35), 0.45, 0.025);
          tl.to(root.querySelectorAll(".s07-co"), { boxShadow: "0 0 22px rgba(184,25,58,0.55)", borderColor: "rgba(184,25,58,0.8)", duration: 0.2, stagger: 0.03 }, at(31.9));
    """, aura=(160, 380), crumb=CH[2])

    # ---------------------------------------------------------------- s08 500+ messages, spam
    cards = "".join(
        f'<div class="gl s08-m" data-layout-allow-occlusion style="left: {150 + i * 26}px; top: {470 + i * 34}px; transform: rotate({[-6, -3, 0, 3, 6][i]}deg)"><span class="ph" style="position:absolute;left:30px;top:40px;width:260px"></span><span class="ph" style="position:absolute;left:30px;top:76px;width:420px"></span><span class="ph" style="position:absolute;left:30px;top:108px;width:380px"></span><span class="s08-hi" data-layout-allow-overlap>Hi! I\'m a web designer...</span></div>'
        for i in range(5))
    panel("s08-spam", 32.72, 35.95, """
        .s08-m { width: 680px; height: 200px; }
        .s08-hi { position: absolute; left: 30px; top: 140px; font-weight: 700; font-size: 30px; color: #cfcdca; }
        #s08-n { position: absolute; left: 0; right: 0; top: 230px; text-align: center; font-size: 190px; text-shadow: 0 0 40px rgba(184,25,58,0.45); }
        #s08-lbl { position: absolute; left: 0; right: 0; top: 420px; text-align: center; font-family: "Inter Tight", Arial, sans-serif; font-weight: 700; font-size: 34px; color: #9a9895; z-index: 3; }
        #s08-stamp { left: 330px; top: 700px; z-index: 4; font-size: 120px; }
    """, f"""
        {cards}
        <div class="big-num" id="s08-n">0</div>
        <div id="s08-lbl">messages sent</div>
        <div class="stamp" id="s08-stamp" data-layout-allow-overlap data-layout-allow-occlusion>SPAM</div>
    """, """
          root.querySelectorAll(".s08-m").forEach((el, i) => {
            tl.fromTo(el, { opacity: 0, x: -300, rotation: -14 }, { opacity: 1, x: 0, rotation: [-6, -3, 0, 3, 6][i], duration: 0.4, ease: "power3.out" }, at(32.8 + i * 0.12));
          });
          fx.count(tl, "#s08-n", 0, 500, at(33.21), 0.75, (v) => Math.round(v) + (v >= 499.5 ? "+" : ""));
          fx.blurIn(tl, "#s08-lbl", at(33.83), { y: 10, blur: 6 });
          fx.stamp(tl, "#s08-stamp", at(35.37), -8);
          fx.shake(tl, root.querySelectorAll(".s08-m"), at(35.55), 10);
    """, aura=(160, 300), crumb=None)

    # ---------------------------------------------------------------- s09 and the result?
    panel("s09-result", 35.95, 39.40, """
        #s09-head { top: 230px; font-size: 80px; }
        #s09-box { left: 140px; top: 500px; width: 800px; height: 430px; }
        .s09-r { position: absolute; left: 44px; right: 44px; height: 140px; }
        .s09-r .k { position: absolute; left: 0; top: 0; font-weight: 700; font-size: 34px; color: #bdbbb8; }
        .s09-r .v { position: absolute; right: 0; top: -14px; font-size: 76px; }
        .s09-r .track { position: absolute; left: 0; right: 0; top: 78px; height: 26px; border-radius: 13px; background: rgba(255,255,255,0.08); overflow: hidden; }
        .s09-r .fill { position: absolute; left: 0; top: 0; width: 100%; height: 100%; border-radius: 13px; transform-origin: 0% 50%; }
    """, """
        <div class="lc-head" id="s09-head"><span id="s09-h1">And The</span><span class="lc-it" id="s09-h2">Result?</span></div>
        <div class="gl" id="s09-box">
          <div class="s09-r" style="top: 70px"><span class="k">Sent</span><span class="v big-num">500</span><div class="track"><div class="fill" id="s09-f1" style="background: #f5f5f5"></div></div></div>
          <div class="s09-r" style="top: 250px"><span class="k">Replied</span><span class="v big-num" id="s09-rep" style="color: #ff4d63">~0</span><div class="track"><div class="fill" id="s09-f2" style="background: #b8193a"></div></div></div>
        </div>
    """, """
          fx.typeSpan(tl, "#s09-h1", at(35.99), at(36.9));
          fx.typeSpan(tl, "#s09-h2", at(36.96), at(37.5));
          fx.blurIn(tl, "#s09-box", at(36.3));
          tl.fromTo("#s09-f1", { scaleX: 0 }, { scaleX: 1, duration: 0.6, ease: "power2.out" }, at(36.6));
          tl.fromTo("#s09-f2", { scaleX: 0 }, { scaleX: 0.012, duration: 0.4, ease: "power2.out" }, at(37.8));
          fx.pop(tl, "#s09-rep", at(38.28), { from: 0.5 });
          fx.shake(tl, "#s09-rep", at(38.7), 8);
    """, aura=(160, 360), crumb=None)

    # ---------------------------------------------------------------- s10 opened + clicked
    rows_html = "".join(
        f'<div class="s10-row" style="top: {84 + i * 92}px"><span class="ph" style="position:absolute;left:30px;top:30px;width:{[220, 180, 240, 200][i]}px"></span>'
        f'<span class="check s10-o" style="position:absolute;left:330px;top:18px">Opened</span><span class="check s10-c" style="position:absolute;left:520px;top:18px">Clicked portfolio</span></div>'
        for i in range(4))
    panel("s10-opened", 39.40, 44.38, """
        #s10-head { top: 210px; }
        #s10-head2 { top: 290px; }
        #s10-box { left: 80px; top: 470px; width: 920px; height: 470px; }
        #s10-box .hd2 { position: absolute; left: 30px; top: 26px; font-weight: 800; font-size: 32px; color: #f5f5f5; }
        .s10-row { position: absolute; left: 0; right: 0; height: 80px; border-top: 2px solid rgba(255,255,255,0.06); }
        #s10-eye { position: absolute; right: 30px; top: 22px; }
    """, f"""
        <div class="lc-head" id="s10-head"><span id="s10-h1">They Opened It.</span></div>
        <div class="lc-head" id="s10-head2"><span id="s10-h2a">They</span><span class="lc-it" id="s10-h2b">Clicked It.</span></div>
        <div class="gl" id="s10-box"><span class="hd2">Email tracking</span>
          <svg id="s10-eye" width="46" height="30" viewBox="0 0 46 30"><path d="M2 15 C 12 2, 34 2, 44 15 C 34 28, 12 28, 2 15 Z" fill="none" stroke="#f5f5f5" stroke-width="3" /><circle cx="23" cy="15" r="6" fill="#b8193a" /></svg>
          {rows_html}</div>
    """, """
          fx.blurIn(tl, "#s10-box", at(39.5));
          fx.typeSpan(tl, "#s10-h1", at(41.3), at(42.3));
          fx.typeSpan(tl, "#s10-h2a, #s10-h2b", at(42.8), at(43.7));
          root.querySelectorAll(".s10-o").forEach((el, i) => {
            tl.fromTo(el, { opacity: 0.35, scale: 0.9 }, { opacity: 1, scale: 1, duration: 0.2, ease: "back.out(2)" }, at(41.79 + i * 0.12));
            tl.to(el, { backgroundColor: "#99122b", borderColor: "#b8193a", duration: 0.12 }, at(41.79 + i * 0.12));
          });
          root.querySelectorAll(".s10-c").forEach((el, i) => {
            tl.fromTo(el, { opacity: 0.35, scale: 0.9 }, { opacity: 1, scale: 1, duration: 0.2, ease: "back.out(2)" }, at(42.99 + i * 0.14));
            tl.to(el, { backgroundColor: "#99122b", borderColor: "#b8193a", duration: 0.12 }, at(42.99 + i * 0.14));
          });
    """, aura=(160, 420), crumb=None)

    # ---------------------------------------------------------------- s11 cutaway: nothing (shot A moody)
    cut("s11-cut-nothing", 44.38, 46.97, 2.6, origin="60% 30%", s0=1.0, s1=1.1)

    # ---------------------------------------------------------------- s13 one out of 500
    dots = "".join(f'<i class="s13-d" style="left: {c * 30}px; top: {r * 30}px"></i>' for r in range(20) for c in range(25))
    hot = (7, 17)  # row, col of the yes
    panel("s13-one-of-500", 49.36, 53.35, """
        #s13-head { top: 230px; font-size: 78px; }
        #s13-grid { position: absolute; left: 172px; top: 470px; width: 740px; height: 590px; }
        .s13-d { position: absolute; width: 20px; height: 20px; border-radius: 50%; background: #39393b; }
        #s13-hot { position: absolute; width: 20px; height: 20px; border-radius: 50%; background: #ff3a55; box-shadow: 0 0 24px rgba(255,58,85,0.95); }
        #s13-ring { position: absolute; width: 80px; height: 80px; border-radius: 50%; border: 4px solid rgba(255,58,85,0.9); opacity: 0; }
        #s13-tag { position: absolute; font-size: 34px; }
    """, f"""
        <div class="lc-head" id="s13-head"><span id="s13-h1">One</span><span class="lc-it" id="s13-h2">Out Of 500</span></div>
        <div id="s13-grid">{dots}
          <i id="s13-hot" style="left: {hot[1] * 30}px; top: {hot[0] * 30}px"></i>
          <i id="s13-ring" style="left: {hot[1] * 30 - 30}px; top: {hot[0] * 30 - 30}px"></i>
          <span class="lc-tag" id="s13-tag" style="left: {hot[1] * 30 - 210}px; top: {hot[0] * 30 - 80}px">1 said yes</span></div>
    """, """
          tl.fromTo(root.querySelectorAll(".s13-d"), { opacity: 0, scale: 0 }, { opacity: 1, scale: 1, duration: 0.25, ease: "back.out(2)", stagger: { each: 0.0016, from: "center" } }, at(49.4));
          fx.pop(tl, "#s13-hot", at(50.54), { from: 0, dur: 0.35 });
          tl.fromTo("#s13-ring", { opacity: 1, scale: 0.2 }, { opacity: 0, scale: 1.6, duration: 0.8, ease: "power2.out", repeat: 2, immediateRender: false }, at(50.6));
          tl.to(root.querySelectorAll(".s13-d"), { opacity: 0.45, duration: 0.5, ease: "power1.out" }, at(50.7));
          fx.pop(tl, "#s13-tag", at(50.7), { rot0: -10, rot: -3 });
          fx.typeSpan(tl, "#s13-h1", at(51.19), at(51.5));
          fx.typeSpan(tl, "#s13-h2", at(51.52), at(53.1));
    """, aura=(160, 400))

    # ---------------------------------------------------------------- s14 shopify job
    panel("s14-shopify", 53.35, 61.75, """
        #s14-inv { left: 150px; top: 380px; width: 780px; height: 450px; }
        #s14-inv .t { position: absolute; left: 40px; top: 34px; font-weight: 800; font-size: 44px; letter-spacing: -0.03em; }
        #s14-inv .who { position: absolute; left: 40px; top: 96px; width: 240px; }
        .s14-li { position: absolute; left: 40px; right: 40px; height: 90px; border-top: 2px solid rgba(255,255,255,0.08); display: flex; align-items: center; justify-content: space-between; font-weight: 700; font-size: 38px; }
        #s14-amt { font-size: 64px; color: #f5f5f5; }
        #s14-warn { position: absolute; left: 150px; top: 860px; display: inline-flex; align-items: center; gap: 12px; }
        #s14-prog { left: 150px; top: 950px; width: 780px; height: 170px; }
        #s14-prog .k { position: absolute; left: 34px; top: 26px; font-weight: 800; font-size: 34px; }
        #s14-prog .pct { position: absolute; right: 34px; top: 22px; font-size: 40px; }
        #s14-prog .track { position: absolute; left: 34px; right: 34px; top: 96px; height: 30px; border-radius: 15px; background: rgba(255,255,255,0.08); overflow: hidden; }
        #s14-fill { position: absolute; left: 0; top: 0; width: 100%; height: 100%; border-radius: 15px; background: linear-gradient(90deg, #99122b, #e0324f); transform-origin: 0% 50%; }
        #s14-done { position: absolute; left: 330px; top: 20px; font-size: 26px; padding: 6px 16px; }
    """, """
        <div class="gl" id="s14-inv"><span class="t">Invoice</span><span class="ph who"></span>
          <div class="s14-li" style="top: 170px"><span id="s14-item">Shopify site</span><span class="big-num" id="s14-amt">$0</span></div>
          <div class="s14-li" style="top: 280px; color: #9a9895; font-size: 30px"><span>Client</span><span>Local company</span></div></div>
        <span class="lc-chip" id="s14-warn"><svg width="34" height="30" viewBox="0 0 34 30"><path d="M17 3 L32 28 H2 Z" fill="none" stroke="#ff4d63" stroke-width="3.5" stroke-linejoin="round"/><path d="M17 12 V19 M17 23 V24" stroke="#ff4d63" stroke-width="3.5" stroke-linecap="round"/></svg>Outside my expertise</span>
        <div class="gl" id="s14-prog"><span class="k">Mission</span><span class="lc-tag" id="s14-done">Complete</span><span class="big-num pct" id="s14-pct">0%</span><div class="track"><div id="s14-fill"></div></div></div>
    """, """
          fx.blurIn(tl, "#s14-inv", at(53.4));
          fx.typeSpan(tl, "#s14-item", at(53.5), at(54.6));
          fx.count(tl, "#s14-amt", 0, 350, at(54.78), 1.25, (v) => "$" + Math.round(v));
          tl.fromTo("#s14-amt", { scale: 1 }, { scale: 1.15, duration: 0.15, ease: "power2.out", yoyo: true, repeat: 1 }, at(56.01));
          fx.pop(tl, "#s14-warn", at(56.8), { rot0: -8, rot: -2 });
          fx.shake(tl, "#s14-warn", at(58.3), 9);
          fx.blurIn(tl, "#s14-prog", at(59.05));
          tl.fromTo("#s14-fill", { scaleX: 0 }, { scaleX: 1, duration: 0.9, ease: "power2.inOut" }, at(60.45));
          fx.count(tl, "#s14-pct", 0, 100, at(60.45), 0.9, (v) => Math.round(v) + "%");
          fx.pop(tl, "#s14-done", at(61.24));
    """, aura=(160, 380), crumb=CH[3])

    # ---------------------------------------------------------------- s15 cutaway: happy in the moment (shot C)
    cut("s15-cut-happy", 61.75, 64.40, 16.8, origin="62% 26%", s0=1.0, s1=1.12)

    # ---------------------------------------------------------------- s16 proof = demand, but not the solution
    import math
    people = []
    k = 0
    for ring, n in ((150, 10), (230, 16), (300, 22)):
        for j in range(n):
            ang = 2 * math.pi * j / n + ring
            x, y = 540 + ring * math.cos(ang) - 16, 740 + ring * math.sin(ang) - 18
            people.append(f'<svg class="s16-p" style="left: {x:.0f}px; top: {y:.0f}px" width="32" height="36" viewBox="0 0 32 36"><circle cx="16" cy="10" r="8" fill="#d24a62"/><path d="M2 36 C 2 22, 30 22, 30 36 Z" fill="#d24a62"/></svg>')
            k += 1
    panel("s16-demand", 64.40, 69.05, """
        #s16-head { top: 250px; font-size: 80px; }
        #s16-head2 { top: 250px; font-size: 80px; opacity: 0; }
        #s16-circ { position: absolute; left: 200px; top: 400px; width: 680px; height: 680px; border-radius: 50%; border: 3px solid rgba(255,255,255,0.35); }
        .s16-p { position: absolute; opacity: 0.85; }
        #s16-core { left: 465px; top: 665px; width: 150px; height: 150px; display: flex; align-items: center; justify-content: center; font-size: 70px; font-weight: 800; color: #f5f5f5; }
        #s16-x { position: absolute; left: 0; right: 0; top: 680px; text-align: center; }
    """, f"""
        <div class="lc-head" id="s16-head"><span id="s16-h1">Proof =</span><span class="lc-it" id="s16-h2">Demand</span></div>
        <div class="lc-head" id="s16-head2"><span id="s16-k1">But Not The</span><span class="lc-it" id="s16-k2">Solution</span></div>
        <div id="s16-circ"></div>
        {''.join(people)}
        <div class="gl crim" id="s16-core">$</div>
    """, """
          fx.blurIn(tl, "#s16-circ", at(64.5), { y: 0, scale: 0.9 });
          fx.pop(tl, "#s16-core", at(64.7));
          tl.fromTo(root.querySelectorAll(".s16-p"), { opacity: 0, scale: 0 }, { opacity: 0.85, scale: 1, duration: 0.25, ease: "back.out(2.4)", stagger: { each: 0.018, from: "random" } }, at(65.3));
          fx.typeSpan(tl, "#s16-h1", at(65.3), at(65.8));
          fx.typeSpan(tl, "#s16-h2", at(65.95), at(66.5));
          tl.to("#s16-head", { opacity: 0, filter: "blur(12px)", duration: 0.3, ease: "power2.in" }, at(66.72));
          tl.fromTo("#s16-head2", { opacity: 0 }, { opacity: 1, duration: 0.01 }, at(67.0));
          fx.typeSpan(tl, "#s16-k1, #s16-k2", at(67.05), at(68.5));
          tl.to([...root.querySelectorAll(".s16-p"), "#s16-circ", "#s16-core"], { opacity: 0.18, filter: "blur(3px)", duration: 0.6, ease: "power2.out" }, at(67.3));
    """, aura=(160, 400))

    # ---------------------------------------------------------------- s17 the template (user's screen recording)
    # content region of screen.mp4 is x 86–994, y 648–1262 (1080x1920 source); fit 936 wide inside the browser panel
    sc = 936 / 908
    panel("s17-template", 69.05, 74.35, f"""
        #s17-box {{ left: 72px; top: 400px; width: 936px; height: 692px; }}
        #s17-view {{ position: absolute; left: 0; top: 52px; width: 936px; height: 640px; overflow: hidden; background: #f3f3f3; }}
        #s17-view video {{ position: absolute; left: {-86 * sc:.1f}px; top: {-648 * sc + (640 - 614 * sc) / 2:.1f}px; width: {1080 * sc:.1f}px; height: {1920 * sc:.1f}px; object-fit: cover; }}
        #s17-stamp {{ left: 250px; top: 650px; z-index: 4; font-size: 104px; }}
        #s17-price {{ position: absolute; left: 700px; top: 1030px; z-index: 5; font-size: 40px; display: inline-flex; align-items: center; gap: 10px; }}
    """, """
        <div class="gl crim" id="s17-box"><div class="bar3"><i></i><i></i><i></i><b></b></div>
          <div id="s17-view"><video id="s17-v" class="clip" src="assets/video/screen.mp4" data-start="0" data-duration="5.3" data-media-start="0.8" data-playback-rate="2" data-track-index="0" muted playsinline></video></div></div>
        <div class="stamp" id="s17-stamp">AMATEUR</div>
        <span class="lc-pill" id="s17-price">$350 <svg width="30" height="34" viewBox="0 0 30 34"><path d="M15 3 V29 M5 19 L15 30 L25 19" stroke="#fff" stroke-width="4.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/></svg></span>
    """, """
          fx.blurIn(tl, "#s17-box", at(69.1), { y: 60 });
          tl.fromTo("#s17-box", { rotationX: 14, transformPerspective: 1600 }, { rotationX: 0, duration: 0.7, ease: "expo.out" }, at(69.1));
          fx.stamp(tl, "#s17-stamp", at(71.23), -8);
          fx.shake(tl, "#s17-box", at(71.45), 8);
          fx.pop(tl, "#s17-price", at(73.34), { rot0: 12, rot: 4 });
          tl.to("#s17-price", { y: 18, duration: 0.25, ease: "power2.in", yoyo: true, repeat: 1 }, at(74.0));
    """, aura=(160, 420), crumb=("Chapter 03", "The Template"))

    # ---------------------------------------------------------------- s18 $350 vs $1,500 minimum
    panel("s18-price", 74.35, 79.02, """
        #s18-head { top: 300px; font-size: 80px; }
        #s18-box { left: 90px; top: 480px; width: 900px; height: 560px; }
        .s18-r { position: absolute; left: 44px; right: 44px; height: 200px; }
        .s18-r .k { position: absolute; left: 0; top: 0; font-weight: 700; font-size: 32px; color: #bdbbb8; }
        .s18-r .v { position: absolute; right: 0; top: -12px; font-size: 80px; }
        .s18-r .track { position: absolute; left: 0; right: 0; top: 90px; height: 64px; border-radius: 16px; background: rgba(255,255,255,0.06); overflow: hidden; }
        .s18-r .fill { position: absolute; left: 0; top: 0; width: 100%; height: 100%; border-radius: 16px; transform-origin: 0% 50%; }
    """, """
        <div class="lc-head" id="s18-head"><span id="s18-h1">Minimum:</span><span class="lc-it" id="s18-h2">$1,500</span></div>
        <div class="gl" id="s18-box">
          <div class="s18-r" style="top: 70px"><span class="k">What I charged</span><span class="v big-num" style="color: #ff4d63">$350</span><div class="track"><div class="fill" id="s18-f1" style="background: #b8193a"></div></div></div>
          <div class="s18-r" style="top: 310px"><span class="k">A website, minimum</span><span class="v big-num" id="s18-v2">$0</span><div class="track"><div class="fill" id="s18-f2" style="background: #f5f5f5"></div></div></div>
        </div>
    """, """
          fx.blurIn(tl, "#s18-box", at(74.4));
          tl.fromTo("#s18-f1", { scaleX: 0 }, { scaleX: 0.233, duration: 0.5, ease: "power2.out" }, at(74.6));
          fx.typeSpan(tl, "#s18-h1", at(76.68), at(77.2));
          fx.typeSpan(tl, "#s18-h2", at(77.36), at(78.6));
          tl.fromTo("#s18-f2", { scaleX: 0 }, { scaleX: 1, duration: 1.4, ease: "power2.out" }, at(77.36));
          fx.count(tl, "#s18-v2", 0, 1500, at(77.36), 1.4, (v) => "$" + Math.round(v).toLocaleString("en-US"));
          tl.fromTo("#s18-v2", { scale: 1 }, { scale: 1.12, duration: 0.18, ease: "power2.out", yoyo: true, repeat: 1 }, at(78.8));
    """, aura=(160, 420), crumb=None)

    # ---------------------------------------------------------------- s19 cutaway: freelancer, not a good one (shot A)
    cut("s19-cut-freelancer", 79.02, 83.25, 0.3, origin="62% 32%", s0=1.0, s1=1.12)

    # ---------------------------------------------------------------- s20 copies prove nothing
    copies = "".join(
        f'<div class="s20-c" style="left: {120 + i * 150}px; top: {470 + i * 90}px; z-index: {3 - i}"><img src="assets/img/template-hero.jpg" alt="" /><span class="lc-tag s20-t">Copy {i + 1}</span></div>'
        for i in range(3))
    panel("s20-copied", 83.25, 88.78, """
        #s20-head { top: 220px; }
        #s20-head2 { top: 300px; font-size: 76px; }
        .s20-c { position: absolute; width: 540px; height: 366px; border-radius: 18px; overflow: hidden; border: 3px solid rgba(255,255,255,0.2); box-shadow: 0 30px 70px rgba(0,0,0,0.7); background: #eee; }
        .s20-c img { display: block; width: 540px; height: 366px; object-fit: cover; }
        .s20-t { position: absolute; left: 16px; top: 16px; }
    """, f"""
        <div class="lc-head" id="s20-head"><span id="s20-h1">A Copied Portfolio</span></div>
        <div class="lc-head" id="s20-head2"><span id="s20-h2a">Proves</span><span class="lc-it" id="s20-h2b">Nothing</span></div>
        {copies}
    """, """
          root.querySelectorAll(".s20-c").forEach((el, i) => {
            tl.fromTo(el, { opacity: 0, x: -150 * i, y: -90 * i, scale: 0.95 }, { opacity: 1, x: 0, y: 0, scale: 1, duration: 0.45, ease: "power3.out" }, at(83.4 + i * 0.35));
          });
          fx.typeSpan(tl, "#s20-h1", at(85.97), at(86.9));
          fx.typeSpan(tl, "#s20-h2a, #s20-h2b", at(87.18), at(88.2));
          tl.to(root.querySelectorAll(".s20-c"), { filter: "grayscale(1) brightness(0.45)", duration: 0.5, ease: "power1.out", stagger: 0.08 }, at(87.54));
          tl.to(root.querySelectorAll(".s20-t"), { backgroundColor: "#3a393a", duration: 0.3 }, at(87.6));
    """, aura=(160, 420))

    # ---------------------------------------------------------------- s22 good portfolio -> lucrative contracts
    panel("s22-good-portfolio", 92.33, 97.23, """
        #s22-tile { left: 390px; top: 380px; width: 300px; height: 250px; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 14px; }
        #s22-tile .nm { font-weight: 800; font-size: 40px; letter-spacing: -0.03em; text-align: center; line-height: 1.02; }
        #s22-svg { position: absolute; left: 0; top: 0; width: 1080px; height: 1920px; overflow: visible; }
        #s22-pill { left: 300px; top: 780px; }
        #s22-c1 { left: 170px; top: 990px; }
        #s22-c2 { left: 640px; top: 990px; }
    """, """
        <svg id="s22-svg" viewBox="0 0 1080 1920" data-layout-allow-overflow>
          <path class="lc-wire s22-w" d="M 470 630 C 470 700, 470 720, 470 778" pathLength="1" stroke-dasharray="1" stroke-dashoffset="1" />
          <path class="lc-wire s22-w" d="M 540 630 C 540 700, 540 720, 540 778" pathLength="1" stroke-dasharray="1" stroke-dashoffset="1" />
          <path class="lc-wire s22-w" d="M 610 630 C 610 700, 610 720, 610 778" pathLength="1" stroke-dasharray="1" stroke-dashoffset="1" />
          <path class="lc-wire-dash" id="s22-d" d="M 540 870 V 930 H 300 V 990 M 540 930 H 780 V 990" />
          <circle class="lc-node" id="s22-node" cx="540" cy="930" r="11" />
        </svg>
        <div class="gl" id="s22-tile"><svg width="76" height="76" viewBox="0 0 54 54"><rect x="3" y="3" width="48" height="48" rx="12" fill="#5b5bd6"/><path d="M27 12 L31 22 L42 22 L33 29 L36 40 L27 33 L18 40 L21 29 L12 22 L23 22 Z" fill="#fff"/></svg><span class="nm" id="s22-nm">Good Portfolio</span></div>
        <div class="lc-pill" id="s22-pill">Lucrative Contracts</div>
        <div class="lc-chip" id="s22-c1">Trust</div>
        <div class="lc-chip" id="s22-c2">Better Clients</div>
    """, """
          fx.blurIn(tl, "#s22-tile", at(94.0));
          fx.typeSpan(tl, "#s22-nm", at(94.06), at(94.8));
          fx.draw(tl, root.querySelectorAll(".s22-w"), at(95.1), 0.5, 0.06);
          fx.pop(tl, "#s22-pill", at(95.74));
          tl.fromTo("#s22-d", { opacity: 0 }, { opacity: 1, duration: 0.25 }, at(96.3));
          fx.pop(tl, "#s22-node", at(96.3), { from: 0 });
          tl.fromTo(["#s22-c1", "#s22-c2"], { opacity: 0, y: 20 }, { opacity: 1, y: 0, duration: 0.3, ease: "power3.out", stagger: 0.12 }, at(96.4));
    """, aura=(160, 380), crumb=CH[4])

    # ---------------------------------------------------------------- s23 locked in
    panel("s23-locked", 97.23, 101.50, """
        #s23-head { top: 230px; font-size: 84px; }
        #s23-lock { left: 410px; top: 400px; width: 260px; height: 260px; display: flex; align-items: center; justify-content: center; }
        .s23-row { top: 740px; }
        .s23-row .strike { position: absolute; left: 140px; width: 560px; top: 55px; height: 7px; border-radius: 4px; background: #e0324f; box-shadow: 0 0 14px rgba(224,50,79,0.7); transform-origin: 0% 50%; }
    """, """
        <div class="lc-head" id="s23-head"><span id="s23-h1">I</span><span class="lc-it" id="s23-h2">Locked In</span></div>
        <div class="gl crim" id="s23-lock"><svg width="150" height="170" viewBox="0 0 150 170"><path id="s23-shackle" d="M40 80 V52 a35 35 0 0 1 70 0 V80" stroke="#f5f5f5" stroke-width="14" fill="none" stroke-linecap="round"/><rect x="22" y="78" width="106" height="84" rx="16" fill="#b8193a"/><circle cx="75" cy="114" r="10" fill="#f5f5f5"/><rect x="71" y="118" width="8" height="22" rx="4" fill="#f5f5f5"/></svg></div>
        <div class="row s23-row" id="s23-r1" style="top: 740px"><span class="tab"></span><span class="num">01</span><span class="txt">Posting</span><span class="strike" id="s23-s1"></span></div>
        <div class="row s23-row" id="s23-r2" style="top: 890px"><span class="tab"></span><span class="num">02</span><span class="txt">Spamming</span><span class="strike" id="s23-s2"></span></div>
    """, """
          fx.typeSpan(tl, "#s23-h1, #s23-h2", at(97.58), at(98.2));
          fx.blurIn(tl, "#s23-lock", at(97.3));
          tl.fromTo("#s23-shackle", { y: -26 }, { y: 0, duration: 0.18, ease: "power4.in" }, at(97.95));
          fx.shake(tl, "#s23-lock", at(98.13), 6);
          fx.blurIn(tl, "#s23-r1", at(98.45), { y: 0, blur: 8 });
          tl.fromTo("#s23-s1", { scaleX: 0 }, { scaleX: 1, duration: 0.25, ease: "power2.out" }, at(99.16));
          tl.to("#s23-r1", { opacity: 0.5, duration: 0.3 }, at(99.45));
          fx.blurIn(tl, "#s23-r2", at(99.95), { y: 0, blur: 8 });
          tl.fromTo("#s23-s2", { scaleX: 0 }, { scaleX: 1, duration: 0.25, ease: "power2.out" }, at(100.74));
          tl.to("#s23-r2", { opacity: 0.5, duration: 0.3 }, at(101.0));
    """, aura=(160, 380))

    # ---------------------------------------------------------------- s24 studied the best
    cards = []
    scatter = [(80, 430, -9), (720, 400, 8), (60, 820, 6), (760, 840, -7), (420, 360, 3), (430, 900, -4)]
    grid = [(90, 470), (400, 470), (710, 470), (90, 690), (400, 690), (710, 690)]
    looks = [("#111", "#e0324f"), ("#f2f2f2", "#111"), ("#151a2e", "#5b8cff"), ("#f6efe6", "#c26b2e"), ("#0f0f10", "#f5f5f5"), ("#eef3f1", "#1f8a5b")]
    for i, ((x, y, r), (bg, ac)) in enumerate(zip(scatter, looks)):
        cards.append(
            f'<div class="s24-c" id="s24-c{i}" style="left: {x}px; top: {y}px; background: {bg}" data-r="{r}">'
            f'<i style="left: 16px; top: 16px; width: 70px; height: 10px; background: {ac}"></i>'
            f'<i style="left: 16px; top: 44px; width: 150px; height: 22px; background: {ac}; opacity: 0.85"></i>'
            f'<i style="left: 16px; top: 74px; width: 110px; height: 22px; background: {ac}; opacity: 0.6"></i>'
            f'<i style="left: 176px; top: 40px; width: 88px; height: 120px; background: {ac}; opacity: 0.35"></i>'
            f'<i style="left: 16px; top: 128px; width: 70px; height: 24px; border-radius: 12px; background: {ac}"></i></div>')
    gx = ",".join(str(g[0]) for g in grid)
    gy = ",".join(str(g[1]) for g in grid)
    sx = ",".join(str(s[0]) for s in scatter)
    sy = ",".join(str(s[1]) for s in scatter)
    panel("s24-studied", 101.50, 106.62, """
        #s24-head { top: 230px; font-size: 80px; }
        .s24-c { position: absolute; width: 280px; height: 190px; border-radius: 14px; overflow: hidden; border: 2px solid rgba(255,255,255,0.22); box-shadow: 0 0 26px rgba(255,255,255,0.08), 0 30px 60px rgba(0,0,0,0.6); }
        .s24-c i { position: absolute; display: block; border-radius: 5px; }
        #s24-ball { left: 425px; top: 600px; z-index: 3; }
        #s24-pill { left: 340px; top: 960px; }
    """, f"""
        <div class="lc-head" id="s24-head"><span id="s24-h1">Studied</span><span class="lc-it" id="s24-h2">The Best</span></div>
        {''.join(cards)}
        <div class="lc-ball" id="s24-ball">Best Portfolios</div>
        <div class="lc-pill" id="s24-pill">New Strategy</div>
    """, f"""
          const GX = [{gx}], GY = [{gy}], SX = [{sx}], SY = [{sy}];
          fx.typeSpan(tl, "#s24-h1", at(101.86), at(102.2));
          fx.typeSpan(tl, "#s24-h2", at(102.19), at(103.0));
          fx.pop(tl, "#s24-ball", at(101.6), {{ from: 0.3, dur: 0.55, ease: "back.out(1.8)" }});
          root.querySelectorAll(".s24-c").forEach((el, i) => {{
            const r = parseFloat(el.dataset.r);
            tl.fromTo(el, {{ opacity: 0, scale: 0.6, rotation: r * 2, filter: "blur(12px)" }}, {{ opacity: 1, scale: 1, rotation: r, filter: "blur(0px)", duration: 0.5, ease: "expo.out" }}, at(102.26 + i * 0.12));
            tl.to(el, {{ y: [-14, 12, -10, 14, 10, -12][i], duration: 1.4, ease: "sine.inOut" }}, at(102.9));
            // "everything changed": snap into an ordered grid
            tl.to(el, {{ x: GX[i] - SX[i], y: GY[i] - SY[i], rotation: 0, duration: 0.6, ease: "expo.inOut" }}, at(104.6 + i * 0.03));
          }});
          tl.to("#s24-ball", {{ opacity: 0, scale: 0.5, duration: 0.35, ease: "power2.in" }}, at(104.6));
          fx.pop(tl, "#s24-pill", at(105.9));
    """, aura=(160, 380))

    # ---------------------------------------------------------------- s25 CTA
    icons = [
        '<svg viewBox="0 0 54 54"><rect x="3" y="3" width="48" height="48" rx="12" fill="#c2304b"/><path d="M13 16h5l4 17h15l4-12H21" stroke="#fff" stroke-width="3.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/><circle cx="24" cy="39.5" r="2.8" fill="#fff"/><circle cx="35" cy="39.5" r="2.8" fill="#fff"/></svg>',
        '<svg viewBox="0 0 54 54"><rect x="3" y="3" width="48" height="48" rx="12" fill="#2f6bf0"/><path d="M12 27 L42 13 L33 42 L27 31 Z" fill="#fff"/><path d="M27 31 L42 13" stroke="#2f6bf0" stroke-width="2.6"/></svg>',
        '<svg viewBox="0 0 54 54"><rect x="3" y="3" width="48" height="48" rx="12" fill="#e0902a"/><path d="M15 21h24l-2.4 21H17.4z" fill="#fff"/><path d="M21 21v-3.5a6 6 0 0 1 12 0V21" stroke="#fff" stroke-width="3.4" fill="none"/></svg>',
        '<svg viewBox="0 0 54 54"><rect x="3" y="3" width="48" height="48" rx="12" fill="#5b5bd6"/><circle cx="24" cy="24" r="9.5" stroke="#fff" stroke-width="4" fill="none"/><path d="M31.5 31.5 L40 40" stroke="#fff" stroke-width="4.6" stroke-linecap="round"/></svg>',
    ]
    tiles = "".join(f'<div class="lc-tile s25-t" style="left: {70 + i * 240}px; top: 560px"><span class="ico">{icons[i]}</span><span class="rule"></span><span class="n">0{i + 1}</span><span class="lab"></span></div>' for i in range(4))
    panel("s25-cta", 106.62, 114.20, """
        #s25-hub { top: 160px; }
        #s25-hub2 { top: 160px; }
        .s25-t .ico { display: block; }
        .s25-t .ico svg { display: block; width: 100%; height: 100%; }
        #s25-btn { position: absolute; left: 240px; top: 620px; width: 600px; height: 150px; border-radius: 75px; background: #99122b; border: 3px solid rgba(255,255,255,0.25); box-shadow: 0 0 50px rgba(184,25,58,0.55), 0 30px 70px rgba(0,0,0,0.6); display: flex; align-items: center; justify-content: center; gap: 20px; font-family: "Inter Tight", Arial, sans-serif; font-weight: 800; font-size: 64px; letter-spacing: -0.03em; color: #fff; }
        #s25-done { position: absolute; left: 240px; top: 620px; width: 600px; height: 150px; border-radius: 75px; background: #2a292b; border: 3px solid rgba(255,255,255,0.18); display: flex; align-items: center; justify-content: center; gap: 16px; font-family: "Inter Tight", Arial, sans-serif; font-weight: 800; font-size: 58px; color: #d8d6d3; }
        #s25-ripple { position: absolute; left: 600px; top: 620px; width: 220px; height: 220px; border-radius: 50%; background: rgba(255,90,110,0.45); opacity: 0; }
        #s25-cursor { position: absolute; left: 660px; top: 720px; width: 70px; height: 86px; overflow: visible; z-index: 6; }
    """, f"""
        <div class="lc-hub" id="s25-hub"><span class="l1" id="s25-a1">Web Designers</span><span class="l2"><span id="s25-a2">Want</span> <span class="lc-it" id="s25-a3">Real</span> <span id="s25-a4">Contracts?</span></span></div>
        <div class="lc-hub" id="s25-hub2"><span class="l1" id="s25-b1">Subscribe</span><span class="l2"><span id="s25-b2">I'll Show You</span> <span class="lc-it" id="s25-b3">What Worked</span></span></div>
        {tiles}
        <div id="s25-done" data-layout-allow-overlap><svg width="52" height="52" viewBox="0 0 52 52"><path d="M10 27 L21 38 L43 13" fill="none" stroke="#d8d6d3" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/></svg>Subscribed</div>
        <div id="s25-btn"><svg width="58" height="58" viewBox="0 0 58 58"><path d="M29 8 C 19 8, 14 16, 14 25 V 36 L 9 43 H 49 L 44 36 V 25 C 44 16, 39 8, 29 8 Z" fill="#fff"/><path d="M22 47 C 23 52, 35 52, 36 47" fill="none" stroke="#fff" stroke-width="5" stroke-linecap="round"/></svg>Subscribe</div>
        <div id="s25-ripple"></div>
        <svg id="s25-cursor" viewBox="0 0 70 86"><path d="M6 4 L6 66 L22 52 L33 78 L45 73 L34 47 L56 47 Z" fill="#ffffff" stroke="#111" stroke-width="4" stroke-linejoin="round"/></svg>
    """, """
          fx.typeSpan(tl, "#s25-a1", at(107.45), at(108.07));
          fx.typeSpan(tl, "#s25-a2, #s25-a3, #s25-a4", at(108.14), at(110.0));
          root.querySelectorAll(".s25-t").forEach((el, i) => {
            tl.fromTo(el, { opacity: 0, y: 40, filter: "blur(12px)" }, { opacity: 1, y: 0, filter: "blur(0px)", duration: 0.45, ease: "expo.out" }, at(106.75 + i * 0.12));
            tl.to(el, { y: [-12, 10, -10, 12][i], duration: 1.6, ease: "sine.inOut" }, at(107.4));
          });
          // "subscribe": hub swaps, tiles step back, the button gets clicked
          tl.to("#s25-hub", { opacity: 0, filter: "blur(12px)", duration: 0.25, ease: "power2.in" }, at(110.25));
          tl.fromTo("#s25-hub2", { opacity: 0 }, { opacity: 1, duration: 0.01 }, at(110.35));
          fx.typeSpan(tl, "#s25-b1", at(110.35), at(110.8));
          fx.typeSpan(tl, "#s25-b2, #s25-b3", at(111.87), at(112.9));
          tl.to(root.querySelectorAll(".s25-t"), { y: 330, opacity: 0.25, scale: 0.85, filter: "blur(4px)", duration: 0.45, ease: "power3.inOut", stagger: 0.04 }, at(110.3));
          fx.pop(tl, "#s25-btn", at(110.4), { from: 0.3, dur: 0.45, ease: "back.out(2.2)" });
          tl.fromTo("#s25-cursor", { opacity: 0, x: 260, y: 300 }, { opacity: 1, x: 0, y: 0, duration: 0.4, ease: "power3.out" }, at(110.55));
          tl.to("#s25-cursor", { scale: 0.82, duration: 0.07, ease: "power2.in" }, at(111.0));
          tl.to("#s25-cursor", { scale: 1, duration: 0.18, ease: "back.out(2)" }, at(111.07));
          tl.to("#s25-btn", { scale: 0.93, duration: 0.07, ease: "power2.in" }, at(111.0));
          tl.fromTo("#s25-ripple", { opacity: 1, scale: 0.1 }, { opacity: 0, scale: 1.6, duration: 0.55, ease: "power2.out", immediateRender: false }, at(111.0));
          tl.to("#s25-btn", { opacity: 0, duration: 0.14, ease: "power1.out" }, at(111.08));
          tl.fromTo("#s25-done", { opacity: 0, scale: 0.93 }, { opacity: 1, scale: 1, duration: 0.4, ease: "back.out(2.6)" }, at(111.08));
          tl.to("#s25-cursor", { x: 140, y: 160, opacity: 0, duration: 0.5, ease: "power2.in" }, at(111.6));
    """, aura=(160, 380))

    print("scenes written")


if __name__ == "__main__":
    main()
