#!/usr/bin/env python3
"""Generate the listicle hub scenes (s01, s02, s06, s12, s21) from one template.

The hub is the film's recurring title card (STYLE.md §1): the title, the four chapter tiles floating around a
crimson ball, and on each return one tile flying to the centre as the hero.
    python3 tools/gen_hubs.py
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONTS = (ROOT / "tools/fonts.css.snippet").read_text()

ICONS = [
    # 01 ready-made portfolio: cart
    '<svg viewBox="0 0 54 54"><rect x="3" y="3" width="48" height="48" rx="12" fill="#c2304b"/><path d="M13 16h5l4 17h15l4-12H21" stroke="#fff" stroke-width="3.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/><circle cx="24" cy="39.5" r="2.8" fill="#fff"/><circle cx="35" cy="39.5" r="2.8" fill="#fff"/></svg>',
    # 02 mass outreach: paper plane
    '<svg viewBox="0 0 54 54"><rect x="3" y="3" width="48" height="48" rx="12" fill="#2f6bf0"/><path d="M12 27 L42 13 L33 42 L27 31 Z" fill="#fff"/><path d="M27 31 L42 13" stroke="#2f6bf0" stroke-width="2.6"/></svg>',
    # 03 the $350 client: bag
    '<svg viewBox="0 0 54 54"><rect x="3" y="3" width="48" height="48" rx="12" fill="#e0902a"/><path d="M15 21h24l-2.4 21H17.4z" fill="#fff"/><path d="M21 21v-3.5a6 6 0 0 1 12 0V21" stroke="#fff" stroke-width="3.4" fill="none"/><text x="27" y="38" text-anchor="middle" font-family="Inter Tight, Arial" font-weight="800" font-size="13" fill="#e0902a">$</text></svg>',
    # 04 study the best: magnifier
    '<svg viewBox="0 0 54 54"><rect x="3" y="3" width="48" height="48" rx="12" fill="#5b5bd6"/><circle cx="24" cy="24" r="9.5" stroke="#fff" stroke-width="4" fill="none"/><path d="M31.5 31.5 L40 40" stroke="#fff" stroke-width="4.6" stroke-linecap="round"/></svg>',
]
NAMES = ["Ready-Made Portfolio", "Mass Outreach", "The $350 Client", "Study The Best"]
# cloud positions (left, top) of the small tiles, ball centred at (540, 715)
CLOUD = [(140, 470), (750, 430), (120, 860), (770, 880)]
HERO = (350, 600)  # hero tile 380x336


def tile_html(i, cls_extra=""):
    return (
        f'<div class="lc-tile{cls_extra}" id="T{i}" style="left: {CLOUD[i][0]}px; top: {CLOUD[i][1]}px">'
        f'<span class="ico">{ICONS[i]}</span><span class="rule"></span><span class="n">0{i + 1}</span><span class="lab"></span></div>'
    )


def scene(sid, t0, t1, focus, type_window, label_at, extra_html="", extra_js="", ball=True):
    p = sid.split("-")[0]
    cloud = "\n        ".join(tile_html(i).replace('id="T', f'id="{p}-t') for i in range(4) if i != focus)
    hero = ""
    hero_js = ""
    if focus is not None:
        hx, hy = HERO
        cx, cy = CLOUD[focus]
        hero = (
            f'<div class="lc-tile hero" id="{p}-hero" style="left: {hx}px; top: {hy}px">'
            f'<span class="ico">{ICONS[focus]}</span><span class="rule"></span><span class="n">0{focus + 1}</span>'
            f'<span class="name" id="{p}-name">{NAMES[focus].replace(" ", " ", 1)}</span></div>'
        )
        # fly from the cloud slot (scaled small tile) to the centre
        dx = cx + 95 - (hx + 190)
        dy = cy + 84 - (hy + 168)
        hero_js = f"""
          tl.fromTo("#{p}-hero", {{ x: {dx}, y: {dy}, scale: 0.5, opacity: 0.9 }}, {{ x: 0, y: 0, scale: 1, opacity: 1, duration: 0.6, ease: "expo.out" }}, at({label_at - 0.75:.2f}));
          fx.typeSpan(tl, "#{p}-name", at({label_at:.2f}), at({label_at + 0.9:.2f}));
          tl.to("#{p}-hero", {{ y: -12, duration: 1.6, ease: "sine.inOut", yoyo: true, repeat: 1 }}, at({label_at + 0.2:.2f}));
          tl.to(".{p}-cloud", {{ opacity: 0, filter: "blur(14px)", scale: 0.8, duration: 0.45, ease: "power2.in", stagger: 0.04 }}, at({label_at - 0.8:.2f}));
          tl.to("#{p}-ball", {{ opacity: 0, scale: 0.6, filter: "blur(10px)", duration: 0.4, ease: "power2.in" }}, at({label_at - 0.8:.2f}));"""
    a0, a1, b0, b1 = type_window
    ball_html = f'<div class="lc-ball" id="{p}-ball" style="left: 425px; top: 600px">Fake Portfolio</div>' if ball else ""
    cloud = cloud.replace('class="lc-tile"', f'class="lc-tile {p}-cloud"')
    return f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <!-- Generated by tools/gen_hubs.py: edit the generator, not this file. -->
    <template id="{sid}-template">
      <link rel="stylesheet" href="assets/css/components.css" />
      <link rel="stylesheet" href="assets/css/house.css" />
      <style>
{FONTS}        #{p}-root .lc-tile .ico {{ display: block; }}
        #{p}-root .lc-tile .ico svg {{ display: block; width: 100%; height: 100%; }}
        #{p}-root .lc-tile.hero .name {{ max-width: 330px; }}
      </style>
      <div id="{p}-root" class="scene-root" data-composition-id="{sid}" data-width="1080" data-height="1920">
        <div class="lc-bg"><div class="lc-grid" data-layout-allow-overflow></div><div class="lc-aura" style="left: 160px; top: 340px" data-layout-allow-overflow></div><div class="lc-vignette"></div></div>
        <div class="lc-hub" id="{p}-hub">
          <span class="l1" id="{p}-l1">Don't Do This</span>
          <span class="l2" id="{p}-l2">Look Pro Without A Portfolio</span>
        </div>
        {cloud}
        {ball_html}
        {hero}
        {extra_html}
      </div>
      <script>
        (function () {{
          const T0 = {t0};
          const at = (t) => Math.max(0, t - T0);
          const tl = gsap.timeline({{ paused: true }});
          const root = document.getElementById("{p}-root");
          fx.ambient(tl, root, {t1 - t0:.2f});
          fx.typeSpan(tl, "#{p}-l1", at({a0}), at({a1}));
          fx.typeSpan(tl, "#{p}-l2", at({b0}), at({b1}));
          root.querySelectorAll(".{p}-cloud").forEach((el, i) => {{
            tl.fromTo(el, {{ opacity: 0, scale: 0.6, filter: "blur(14px)", rotation: [-8, 6, 5, -6][i] }}, {{ opacity: 1, scale: 1, filter: "blur(0px)", rotation: [-5, 4, 3, -4][i], duration: 0.5, ease: "expo.out" }}, at(T0 + 0.05 + i * 0.07));
            tl.to(el, {{ y: [-16, 12, -10, 14][i], duration: {max(1.0, t1 - t0 - 0.6):.2f}, ease: "sine.inOut" }}, at(T0 + 0.55));
          }});
          {"tl.fromTo('#" + p + "-ball', { scale: 0.3, opacity: 0 }, { scale: 1, opacity: 1, duration: 0.55, ease: 'back.out(1.8)' }, at(T0 + 0.15));" if ball else ""}
          {hero_js}
          {extra_js}
          window.__timelines["{sid}"] = tl;
        }})();
      </script>
    </template>
  </body>
</html>
"""


def main():
    out = {
        # hook: title types as spoken, cloud + ball, no hero yet
        "s01-hub-hook": scene("s01-hub-hook", 0.0, 5.80, None, (0.09, 1.3, 1.9, 4.1), 0,
                              extra_js='tl.to("#s01-ball", { scale: 1.12, duration: 0.25, ease: "power2.out", yoyo: true, repeat: 1 }, at(4.45));'),
        # "I cheated. I bought a ready-made portfolio." — hero 01 + crimson stamp
        "s02-hero-01": scene("s02-hero-01", 5.80, 9.92, 0, (5.8, 5.81, 5.8, 5.81), 7.05,
                             extra_html='<div class="stamp" id="s02-stamp" style="left: 600px; top: 520px">I CHEATED</div>',
                             extra_js='fx.stamp(tl, "#s02-stamp", at(5.9), 8); fx.shake(tl, "#s02-hero", at(6.12), 8);'),
        "s06-hub-02": scene("s06-hub-02", 23.42, 28.05, 1, (23.45, 23.9, 23.9, 24.6), 25.2),
        "s12-hub-03": scene("s12-hub-03", 46.97, 49.36, 2, (47.0, 47.3, 47.3, 47.8), 48.15),
        "s21-hub-04": scene("s21-hub-04", 88.78, 92.33, 3, (88.8, 89.2, 89.2, 89.9), 90.4),
    }
    for sid, html in out.items():
        (ROOT / f"compositions/{sid}.html").write_text(html)
        print("wrote", sid)


if __name__ == "__main__":
    main()
